cmd/optimize/main.go
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> optimize: $0 -> os.Args[0]

snapshot/snapshot.go
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> error out when no filesystem plugin is installed

cmd/rsnapshotd/main.go
* Create directory if it doesn't exist
* Remove socket if already exists, to avoid EADDRINUSE
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> rsnapshotd: fix creating socket file

snapshot/snapshot.go
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> snapshot: fix error string

cmd/rsnapshotd/main.go, snapshot/snapshot.go
Unmount all mounts (including `Committed` ones) on SIGINT
=> graceful shutdown

script/demo/run.sh, script/integration/containerd/entrypoint.sh, script/integration/docker-compose-integration.yml.sh, script/integration/rsnapshotd/entrypoint.sh, script/make.sh, script/optimize/docker-compose-opt.yml.sh, script/optimize/optimize/entrypoint.sh
=> Make shell scripts safer with pipefail option

cache/cache.go, script/demo/config.stargz.toml, script/integration/containerd-stargz-grpc/config.stargz.toml, script/integration/containerd-stargz-grpc/entrypoint.sh, stargz/fs.go
=> Use directory-based cache by default

script/benchmark/tools/plot.sh
We need enough information for understanding the histogram, aiming to add it to README (#50).
=> Add y-label to benchmarking result histogram and fix the title

stargz/fs.go, stargz/fs_test.go
Currently, we re-authenticating RoundTripper for each reading during prefetch and background-fetch and it costs extra time for each authentication.
https://github.com/containerd/stargz-snapshotter/blob/28ff0b6d5fe9b5a670d2ce46c2d059835033737b/stargz/fs.go#L252
https://github.com/containerd/stargz-snapshotter/blob/28ff0b6d5fe9b5a670d2ce46c2d059835033737b/stargz/fs.go#L280
This commit solves this by enabling sharing transports between prefetch and background-fetch.
=> Avoid duplicated authentications on prefetch and background-fetch

snapshot/snapshot.go
We currently have a recursive acquisition of read-transaction during checking layers availability but this is dangerous because it possibly leads to deadlock on remapping the data file (Related issue: https://github.com/etcd-io/bbolt/pull/59) and we are occasionally seeing this snapshotter hanging because of this issue.
This commit solves this by avoiding nested read transaction.
=> Avoid nested transaction during checking layers availability

cache/cache.go, cmd/ctr-remote/commands/optimize.go, cmd/ctr-remote/logger/logger.go, cmd/ctr-remote/main.go, cmd/ctr-remote/sampler/sampler.go, cmd/ctr-remote/sorter/sorter.go, snapshot/snapshot.go, stargz/reader/reader.go, stargz/reader/reader_test.go, stargz/remote/blob.go, stargz/remote/blob_test.go, stargz/remote/resolver.go, task/task_test.go
Follow-up PR for https://github.com/containerd/stargz-snapshotter/pull/62#pullrequestreview-381763335
=> Refactoring: Use error wrappers

stargz/fs.go, stargz/fs_test.go
Currently stargz snapshotter loses suid,sgid,sticky bits:
```console
---x--x--x 1 root root 212288 Nov 11 15:15 /usr/bin/sudo
```
These bits should be preserved just same as overlayfs snapshotter:
```console
---s--x--x 1 root root 212288 Nov 11 15:15 /usr/bin/sudo
```
=> fs: Do not lose suid,sgid,sticky bits from metadata

.github/workflows/benchmark.yml, .github/workflows/tests.yml
This will fix occasional re-run failure in our CI
See also: https://github.com/actions/checkout/issues/23
=> Bump actions/checkout to v2

README.md
Adding link of recently posted [introductory blog](https://medium.com/nttlabs/startup-containers-in-lightning-speed-with-lazy-image-distribution-on-containerd-243d94522361) to README.
=> Add link to the introductory blog post

Makefile, cmd/ctr-remote/commands/optimize.go, cmd/ctr-remote/logger/logger.go, script/integration/containerd/entrypoint.sh, script/optimize/optimize/entrypoint.sh, stargz/fs.go, task/task.go, task/task_test.go
Detected by the Go race detector (`-race` option).
This commit also enables the race detector at some points in our CI.
=> Fix potential data race

cache/cache.go
Recently, we are seeing warning logs from cache, like this:
```console
Warning: failed to commit cache to "/var/lib/containerd-stargz-grpc/stargz/fscache/bc/bc0c5a8d9a2481f3247bc0c47dc5f86feb5b0e80642dcfc036a689db52fd391f": rename /var/lib/containerd-stargz-grpc/stargz/fscache/bc/w/bc0c5a8d9a2481f3247bc0c47dc5f86feb5b0e80642dcfc036a689db52fd391f /var/lib/containerd-stargz-grpc/stargz/fscache/bc/bc0c5a8d9a2481f3247bc0c47dc5f86feb5b0e80642dcfc036a689db52fd391f: no such file or directory
```
This is because multiple goroutines simultaneously try to commit the same cache contents to the same file.
This commit solves this by adding a per-key named lock which also helps avoid duplication of works by ensuring only one goroutine runs per key.
=> Avoid race condition on writing cache contents to files

script/cri/test.sh
Please see also: https://github.com/kubernetes-sigs/cri-tools/pull/624
=> Use cri-tools 16911795a3c33833fa0ec83dac1ade3172f6989e

cmd/ctr-remote/commands/optimize.go
During optimization, we currently store the layer contents on memory ([]byte)
but it ends up consuming large memory. This commit solves this by storing layers
to temporary files instead.
```
ctr-remote image optimize --plain-http glassfish:4.1-jdk8 http://registry2:5000/glassfish:4.1-jdk8
```
```
(pprof) top
Showing nodes accounting for 513.71MB, 99.02% of 518.78MB total
Dropped 189 nodes (cum <= 2.59MB)
flat  flat%   sum%        cum   cum%
512.02MB 98.70% 98.70%   512.02MB 98.70%  bytes.makeSlice
1.67MB  0.32% 99.02%     3.32MB  0.64%  github.com/google/crfs/stargz.(*Writer).AppendTar
0.01MB 0.0023% 99.02%     3.34MB  0.64%  github.com/containerd/stargz-snapshotter/cmd/ctr-remote/commands.(*layer).Compressed.func1
0     0% 99.02%      512MB 98.69%  bytes.(*Buffer).ReadFrom
0     0% …
```
=> Avoid storing layer contents in memory during optimization

cmd/ctr-remote/commands/optimize.go, cmd/ctr-remote/logger/logger.go, cmd/ctr-remote/sampler/sampler.go
This includes:
- Using logrus for printing logs (Following-up  https://github.com/containerd/stargz-snapshotter/pull/113#pullrequestreview-440517673)
- Refactor the logic in sampler
- Refactor the directory names in workspace to be more debug-friendly
=> Refactor optimize command

.github/workflows/tests.yml, Makefile, go.sum
Among containerd projects, there are commonly used "Project Checks" jobs in Github Actions for checking DCO, file headers and vendor directory validation. We should follow the checking methods with these containerd projects.
Please see also other projects:
- https://github.com/containerd/containerd/blob/a6697c1d5f1d00f3e56048503aef8aa70b9b4170/.github/workflows/ci.yml
- https://github.com/containerd/cri/blob/5df93a038acc017abaab0b037fa7d03dfcab9fe0/.github/workflows/ci.yml
- https://github.com/containerd/cgroups/blob/318312a373405e5e91134d8063d04d59768a1bff/.github/workflows/ci.yml
=> Use Github Acions jobs of project checks commonly used in containerd projects

cmd/ctr-remote/commands/optimize.go
Signed-off-by: Jianming Zhang <zhang.jianming7@zte.com.cn>
=> fix description errors in the optimize-parameter usage instructions

stargz/remote/resolver.go
This commit eliminates URL information from error logs for avoiding potential security risk.
In the future, we may want additional debug logs containing URL information for development purpose but let's keep it separated patch.
=> Eliminate URL information in error logs

cache/cache.go, cmd/containerd-stargz-grpc/main.go, stargz/config/config.go, stargz/fs.go, stargz/keychain/kubeconfig.go, stargz/remote/resolver.go, stargz/remote/resolver_test.go
Currently, each stargz-related package in this project contains its configuration structs. We should put them together as one independent package for ease of importing.
=> Refactoring: add config package

stargz/fs.go
Currently, resolved layer information (`stargz.resolveResult`) is cached for
better `Prepare` performance but there is no caching mechanism on retrying
failed layer resolve. This commit enables to cache valid `remote.Blob`s and to
use them for retrying layer resolve, which allows the snapshotter to bypass some
steps (authn, redirection, getting size info) during the retry.
=> Cache blob information on retrying layer resolve

stargz/handler/handler.go
#144
In containerd, there is a size limit for label size (4096 chars).
If an image has many layers, containerd.io/snapshot/remote/stargz.layers will
hit the limit of label size and the remote snapshot preparation will fail.
This commit fixes this by limiting the size of the label.
=> Limit size of additional label for avoiding preparation failure

docs/verification.md, stargz/config/config.go, stargz/fs.go
Added flag for disabling verification completely - mentioned in https://github.com/containerd/stargz-snapshotter/issues/129#issuecomment-698046132
=> Allow to disable verification completely

stargz/remote/resolver.go
Authorizer in containerd lib requires scope configuration via context. 
Currently our resolver misses this, which leads to fail to connect to registries (e.g. ghcr.io).
This commit fixes the issue.
=> Add scope configration

.github/workflows/tests.yml
https://github.com/containerd/project-checks/
=> Use containerd/project-checks

Dockerfile, README.md, docs/ctr-remote.md, script/demo/config.cni.conflist, script/demo/docker-compose.yml, script/demo/run.sh
This includes updates for the demo environment according to the contents of the doc.
=> Add document about optimization with `ctr-remote`

cmd/ctr-remote/commands/optimize.go, script/optimize/optimize/entrypoint.sh
=> Fix `--no-optimize` option isn't enabled

cmd/containerd-stargz-grpc/main.go, script/integration/containerd/entrypoint.sh
resolve https://github.com/containerd/stargz-snapshotter/issues/13
Signed-off-by: Nozomu Ohki <nozomunoise@gmail.com>
=> Fix to start when there is no config file

docs/ctr-remote.md, docs/overview.md
Signed-off-by: fahedouch <fahed.dorgaa@gmail.com>
=> fix ctr-remote typo

estargz/go.mod
=> Bump go to 1.15 (estargz lib)

cmd/ctr-remote/main.go
=> Fix ctr-remote's subcommands don't override ctr's default

snapshot/snapshot.go
Currently, mount error is unexpectedly hidden on the log output.
This commit fixes this issue.
Before this commit (unexpected):
```
ctr-remote i rpull ghcr.io/stargz-containers/python:3.7-org
...
{"error":null,"key":"default/1/extract-722586395-b02_ sha256:114ca5b7280f3b49e94a67659890aadde83d58a8bde0d9020b2bc8c902c3b9de","level":"debug","msg":"failed to prepare remote snapshot","parent":"","remote-snapshot-prepared":"false","time":"2021-01-29T08:47:45.072267512Z"}
```
Fixed:
```
ctr-remote i rpull ghcr.io/stargz-containers/python:3.7-org
...
{"error":"failed to resolve layer: failed to resolve layer \"sha256:d77915b4e630d47296770ce4cf481894885978072432456615172af463433cc5\" from \"ghcr.io/stargz-containers/python:3.7-org\": failed to resolve layer: failed to read layer: failed to parse …
```
=> Print mount error in the log output

.github/workflows/release.yml, Dockerfile
#253
Release cross builds
This commit adds the following cross builds
- amd64
- arm
- arm64
- ppc64le
- s390x
Note that the test is currently done only against amd64 binaries.
=> Release cross builds

go.mod
=> Release v0.4.1

Dockerfile, docs/overview.md, script/integration/containerd/config.containerd.toml, script/integration/containerd/config.stargz.toml, script/integration/containerd/entrypoint.sh, script/integration/test.sh, script/optimize/optimize/entrypoint.sh, script/optimize/test.sh, script/pullsecrets/run-kind.sh
=> Use nerdctl instead of docker cli in the CI containers

cmd/containerd-stargz-grpc/main.go
=> Check if snapshotter is supported during starting up of the plugin

fs/fs.go, fs/fs_test.go, snapshot/snapshot.go
ref: https://github.com/containerd/containerd/pull/5076
=> overlay: support "userxattr" option (kernel 5.11)

README.md
=> README.md: add useful links

Dockerfile, Makefile, script/benchmark/hello-bench/prepare.sh, snapshot/snapshot.go
Full diff: https://github.com/containerd/nerdctl/compare/v0.5.0...v0.7.3
=> Bump nerdctl to v0.7.3

script/benchmark/config/config.containerd.toml, script/demo/config.containerd.toml, script/integration/containerd/config.containerd.toml
containerd's v1 config file has been deperecated.
=> Switch to v2 config files of containerd in our CI

analyzer/option.go, fs/source/source.go, util/testutil/tar.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Fix golint issues caused by typos

fs/fs.go
=> Fix typos in fs/fs.go

README.md, cmd/stargz-store/main.go, docs/INSTALL.md
I'll prepare for v0.6.0 after this.
=> Add doc about installing stargz store

Dockerfile
This fixes recent CI failures.
=> Enable to build containerd with the latest Makefile

MAINTAINERS
See https://github.com/containerd/project/commit/7d4e3aa73a1d883e62c5c0188151e67e7d6512bb
=> MAINTAINERS: s/MAINTAINERS/COMMITTERS/g

README.md, docs/pre-converted-images.md
Resolves: https://github.com/containerd/stargz-snapshotter/issues/386
=> Add docs about prebuilt kind node image

README.md, docs/pre-converted-images.md
This commit adds a link to `estargz.kontain.me`.
Thanks @imjasonh !
=> Add a link to estargz.kontain.me

Dockerfile
https://github.com/containerd/containerd/blob/5d3e8fd2c07af15964b6b2f1b47dacaa3ed87157/go.mod#L74
We need to update go.mod in submodules as well.
=> Dockerfile: fix containerd + bulitin stargz-snapshotter can't build recently

fs/fs.go, fs/remote/blob.go, fs/remote/resolver.go, service/service.go, snapshot/snapshot.go
This patch adds a few new log lines. It also updates log levels of some
error cases from debug to warn.
Signed-off-by: Sumeet Bhatia <sumee@amazon.com>
=> Add log lines and update log levels to aid debugging

estargz/build_test.go, estargz/go.mod, estargz/go.sum, estargz/testutil.go, estargz/zstdchunked/zstdchunked.go, estargz/zstdchunked/zstdchunked_test.go, go.sum
Alternative of https://github.com/containerd/stargz-snapshotter/pull/438
=> estargz: bump github.com/klauspost/compress v1.12.3 to v1.13.5

fs/layer/node.go
Making a change based on discussion in https://github.com/containerd/stargz-snapshotter/issues/405
Signed-off-by: Viktor Kuznietsov <vkuzniet@amazon.com>
=> Add logging of statFile errors

script/benchmark/hello-bench/src/hello.py
Fixes an error in preparation code of benchmark. This code block is not executed on Github Actions so hasn't affected CI.
=> Fix error in image preparation code of benchmark

script/benchmark/config-containerd/etc/containerd-stargz-grpc/config.toml, script/benchmark/hello-bench/run.sh, script/benchmark/hello-bench/src/hello.py, script/benchmark/test.sh
containerd-stargz-grpc exposes its debug endpoint since e60759e.
Now Hello Bench in "make benchmark" can run "ctr pprof" against
the endpoint.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
=> Run ctr pprof against containerd-stargz-grpc in Hello Bench

script/cri-containerd/test.sh, script/cri-o/test.sh
This seems to cause CI failures recently.
=> CI: do not install unused packages

.github/workflows/tests.yml, Makefile, script/k3s-argo-workflow/go.yaml.template, script/k3s-argo-workflow/run.sh
This attempts to integrate eStargz + k3s + Argo Workflow with a simple example Golang CI.
=> Integration with k3s + argo workflow

util/testutil/tar.go
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>
=> Fix golint issue

script/integration/containerd/entrypoint.sh
Recently we're seeing the following error in our CI.
```
testenv_integration    | tar: Unexpected EOF in archive
testenv_integration    | tar: Unexpected EOF in archive
testenv_integration    | tar: Error is not recoverable: exiting now
```
This commit tries to fix this flakiness by ensuring tar is exported before
container exits.
=> CI: ensure tar is fully exported before container exits

docs/pre-converted-images.md, script/benchmark/hello-bench/src/hello.py
https://github.com/containerd/stargz-snapshotter/issues/546
=> docs: image: add nixos/nix to pre-converted images

cmd/stargz-store/main.go, estargz/estargz.go, fs/reader/reader.go
No logics changed in this change. Only correct some typos.
=> Fix some spelling mistakes

cmd/go.sum, ipfs/go.mod, ipfs/go.sum
=> Bump github.com/ipfs/go-ipfs-files from 0.0.9 to 0.1.0

.github/workflows/nightly.yml
=> CI: fix CRI-O test failure in nightly

snapshot/snapshot.go
When stargz-snapshotter is used as a library, restoring logic sometimes should not be enabled on snapshotter side.
This commit makes enabling/disabling of the restoring logic configurable.
This will be needed for https://github.com/moby/buildkit/issues/2667
=> snapshotter: make restoring configurable

cmd/go.mod, cmd/go.sum, go.mod, go.sum
=> Bump github.com/containerd/continuity from 0.2.2 to 0.3.0

cmd/go.mod, cmd/go.sum, go.mod, go.sum
=> Bump google.golang.org/grpc from 1.45.0 to 1.46.0

Dockerfile, cmd/go.mod, cmd/go.sum, go.mod, go.sum, ipfs/go.mod, ipfs/go.sum
https://github.com/containerd/containerd/releases/tag/v1.6.4
=> Bump up containerd to v1.6.4

cmd/go.sum, estargz/go.mod, estargz/go.sum, go.mod, go.sum
https://github.com/containerd/stargz-snapshotter/pull/780
https://github.com/containerd/stargz-snapshotter/pull/779
=> Bump github.com/klauspost/compress from 1.15.2 to 1.15.3

cmd/go.sum, estargz/go.mod, estargz/go.sum, go.mod, go.sum
https://github.com/containerd/stargz-snapshotter/pull/785
https://github.com/containerd/stargz-snapshotter/pull/786
=> Bump up github.com/klauspost/compress from v1.15.3 to v1.15.4

cmd/go.sum, go.mod, go.sum
=> Bump github.com/prometheus/client_golang from 1.12.1 to 1.12.2

cmd/go.mod, cmd/go.sum, go.mod, go.sum
https://github.com/containerd/stargz-snapshotter/pull/793
https://github.com/containerd/stargz-snapshotter/pull/792
=> Bump google.golang.org/grpc from 1.46.0 to 1.46.2

store/fs.go
=> chore: remove typo in comment

cmd/go.mod, cmd/go.sum, go.mod, go.sum
https://github.com/containerd/stargz-snapshotter/pull/817
=> Bump github.com/moby/sys/mountinfo from 0.6.1 to 0.6.2

cmd/go.sum, estargz/go.mod, estargz/go.sum, go.mod, go.sum
https://github.com/containerd/stargz-snapshotter/pull/837
https://github.com/containerd/stargz-snapshotter/pull/835
=> Bump github.com/klauspost/compress from 1.15.6 to 1.15.7

cmd/go.mod, cmd/go.sum, estargz/go.mod, estargz/go.sum, go.mod, go.sum
- https://github.com/containerd/stargz-snapshotter/pull/850
- https://github.com/containerd/stargz-snapshotter/pull/849
- https://github.com/containerd/stargz-snapshotter/pull/848
- https://github.com/containerd/stargz-snapshotter/pull/847
=> Bump up dependencies

Dockerfile, script/k3s-argo-workflow/run.sh, script/k3s/run-k3s.sh
- update kind node to v1.24.3 which updates the base image from ubuntu:21:10 (EOL) to ubuntu:22:04
- fix k3s CI
=> Deflake CI

cmd/go.mod, cmd/go.sum, go.mod, go.sum
https://github.com/containerd/stargz-snapshotter/pull/858
https://github.com/containerd/stargz-snapshotter/pull/857
=> Bump github.com/sirupsen/logrus from 1.8.1 to 1.9.0

script/k3s-argo-workflow/run.sh
argo-workflow's `stable` branch has been deleted.
=> CI: update argo-workflows to v3.4.3

cmd/go.sum, go.mod, go.sum
- https://github.com/containerd/stargz-snapshotter/pull/974
=> Bump github.com/prometheus/client_golang from 1.13.0 to 1.13.1

cmd/go.mod, cmd/go.sum, go.mod, go.sum
- https://github.com/containerd/stargz-snapshotter/pull/979
- https://github.com/containerd/stargz-snapshotter/pull/980
- https://github.com/containerd/stargz-snapshotter/pull/981
=> go.mod: bump up dependencies

README.md, docs/integration.md, docs/ipfs.md, docs/overview.md
Fixes #988
Related https://github.com/containerd/stargz-snapshotter/issues/258
This commit adds a document about eStargz integration with tools in community.
=> Add document about integrations of eStargz with other tools

cmd/go.mod, cmd/go.sum, go.mod, go.sum
- https://github.com/containerd/stargz-snapshotter/pull/1015
- https://github.com/containerd/stargz-snapshotter/pull/1016
=> Bump up golang.org/x/sys to v0.3.0

cmd/containerd-stargz-grpc/ipfs/resolvehandler.go
Avoid following errors that can occur when stargz-snapshotter tries to read from the ipfs repo while other read is ongoing and the repo is locked.
```
{"error":"exit status 1","level":"debug","msg":"failed to wait for process exit: \"bafybeibb2buketnuvn7r4dwusypy6eskr3ujhhs6wjxijhfsleibv4i3ke\"(offset:2100000,length:50000)","stderr":"Error: lock /root/.ipfs/repo.lock: someone else has the lock\n","time":"2022-12-20T22:21:53.331722954Z"}
{"error":"exit status 1","level":"debug","msg":"failed to wait for process exit: \"bafybeibb2buketnuvn7r4dwusypy6eskr3ujhhs6wjxijhfsleibv4i3ke\"(offset:4300000,length:1350000)","stderr":"Error: lock /root/.ipfs/repo.lock: someone else has the lock\n","time":"2022-12-20T22:21:53.365469640Z"}
{"error":"exit status 1","level":"debug","msg":"failed to wait for …
```
=> IPFS: retry on repository is locked

script/k3s-argo-workflow/run.sh, script/k3s/run-k3s.sh
This is needed to pass the release CI (#1076): https://github.com/containerd/stargz-snapshotter/actions/runs/4001978380/jobs/6868764856#step:8:773
=> CI: k3s: compile with the testing estargz pkg

cmd/go.mod, go.mod
```
- labels: correctly propagate extra labels (#1143)
```
=> Prepare for v0.14.3

.github/workflows/nightly.yml, .github/workflows/tests.yml
Alternative of https://github.com/containerd/stargz-snapshotter/pull/1212
=> CI: re-install the latest docker on runner

Dockerfile, cmd/go.mod, cmd/go.sum, go.mod, go.sum, ipfs/go.mod, ipfs/go.sum
https://github.com/containerd/containerd/releases/tag/v1.7.3
=> bump up containerd to 1.7.3

.github/workflows/nightly.yml, .github/workflows/tests.yml, Dockerfile
- https://github.com/containerd/stargz-snapshotter/pull/1339
=> Bump up Golang to 1.21

Dockerfile, cmd/go.mod, cmd/go.sum, go.mod, go.sum, ipfs/go.mod, ipfs/go.sum
containerd 1.7.7 https://github.com/containerd/containerd/releases/tag/v1.7.7
=> Bump up containerd to v1.7.7

cmd/go.mod, cmd/go.sum, ipfs/go.mod, ipfs/go.sum
- https://github.com/containerd/stargz-snapshotter/pull/1430
=> go.mod: bump github.com/multiformats/go-multiaddr from 0.11.0 to 0.12.0

cmd/go.mod, go.mod
This will contain github release page and release binaries
depends on #1455
=> prepare for v0.15.1

script/k3s-argo-workflow/run.sh, script/k3s/run-k3s.sh
This will fix the recent ci failures.
=> ci: fix k3s ci failures

.github/workflows/nightly.yml, .github/workflows/tests.yml
https://github.com/k3d-io/k3d/releases/tag/v5.6.0
=> ci: Bump up k3d to v5.6.0

Dockerfile, cmd/go.mod, cmd/go.sum, go.mod, go.sum, ipfs/go.mod, ipfs/go.sum
- https://github.com/containerd/stargz-snapshotter/pull/1541
- https://github.com/containerd/stargz-snapshotter/pull/1540
=> Containerd 1.7.13

fs/config/config.go, service/config.go
Markdown version will be following up.
=> Add godoc for configuration structs

Dockerfile, cmd/go.mod, cmd/go.sum, go.mod, go.sum, ipfs/go.mod, ipfs/go.sum
- https://github.com/containerd/stargz-snapshotter/pull/1703
- https://github.com/containerd/stargz-snapshotter/pull/1702
- https://github.com/containerd/stargz-snapshotter/pull/1700
=> Bump up containerd to 1.7.18

.github/workflows/nightly.yml, .github/workflows/tests.yml
https://github.com/k3d-io/k3d/releases/tag/v5.6.3
=> CI: bump k3d to v5.6.3

nativeconverter/zstdchunked/zstdchunked.go
=> [v0.16] Fix zstd:chunked converter error on duplicated blobs

.github/workflows/tests.yml
https://github.com/golangci/golangci-lint/releases/tag/v1.64.2
=> CI: golangci-lint 1.64.2

script/k3s-argo-workflow/run.sh
This PR fixes recent failure in K3sArgoWorkflow CI (https://github.com/containerd/stargz-snapshotter/actions/runs/13514645922/job/37761022412?pr=1962)
=> CI: fix K3sArgoWorkflow failure

Dockerfile, cmd/go.mod, cmd/go.sum, go.mod, go.sum, ipfs/go.mod, ipfs/go.sum
- https://github.com/containerd/stargz-snapshotter/pull/2021
- https://github.com/containerd/stargz-snapshotter/pull/2020
=> containerd v2.0.4

Dockerfile
https://github.com/containerd/containerd/releases/tag/v2.1.2
=> Dockerfile: Bump up containerd to v2.1.2

.github/workflows/tests.yml, script/cri-containerd/test.sh, script/integration/containerd/config.stargz.toml, script/integration/test.sh
=> CI: enable FUSE passthrough in CI

fs/reader/reader.go
fix https://github.com/containerd/stargz-snapshotter/pull/1954/files#r2291454841
=> remove unused firstChunkOffset variable

cmd/ctr-remote/commands/optimize.go, nativeconverter/estargz/estargz.go, nativeconverter/estargz/externaltoc/converter.go
explicitly copying the incoming `commonOpts` inside both `estargzconvert.LayerConvertWithLayerAndCommonOptsFunc` and `esgzexternaltocconvert.LayerConvertWithLayerAndCommonOptsFunc` to eliminate the data race and improve robustness and maintainability, see more at #2132
=> fix potential data race in nativeconverter/estargz
