- filesystems/stargz/fs.go
- filesystems/stargz/fs_test.go
- filesystems/stargz/urlreaderat.go
- filesystems/stargz/urlreaderat_test.go
```console
bash-4.2# ls -l .remote-snapshotter/
total 0
-r-------- 1 root root 158 Jan  1  1970 sha256:0607ddd650101f5f06eee6c34fad2b27685fed68091eb596a78332a7109bc6f7.json
-r-------- 1 root root 161 Jan  1  1970 sha256:3246c6d2bf2222223d0eef83c7ee326ad4d196377c662c589cf1faaca1775fd8.json
-r-------- 1 root root 158 Jan  1  1970 sha256:b9548dfd45572f16c8c86f25650b0edb12bfdc8d89b10cf694343c4d43a143ef.json
bash-4.2# cat .remote-snapshotter/*
{"digest":"sha256:0607ddd650101f5f06eee6c34fad2b27685fed68091eb596a78332a7109bc6f7","size":46628702,
"fetchedSize":4478702,"fetchedPercent":9.605032539829224}
{"digest":"sha256:3246c6d2bf2222223d0eef83c7ee326ad4d196377c662c589cf1faaca1775fd8","size":199093466,
"fetchedSize":61243466,"fetchedPercent":30.761163201609037} …
```
> stargz: export cache usage

- script/integration/containerd-stargz-grpc/entrypoint.sh
- script/integration/containerd/entrypoint.sh
- stargz/filereaderat.go
- stargz/filereaderat_test.go
- stargz/fs.go
- stargz/fs_test.go
- stargz/urlreaderat.go
- stargz/urlreaderat_test.go
- task/task.go
- task/task_test.go
- vendor.conf
Background fetching disturbs more important "frontend" tasks(=authentication, redirection, reading files, etc...) so this commit includes a small task manager for less important "preemptive" tasks.
This is related to #30 and possibly give us performance improvement for unoptimized images(mentioned in #29).
> Fetch whole layer in background

- Makefile
- NOTICE.md
- cache/cache_test.go
- cmd/ctr-remote/commands/optimize.go
- cmd/ctr-remote/logger/logger_test.go
- cmd/ctr-remote/sampler/sampler.go
- cmd/ctr-remote/sorter/sorter_test.go
- stargz/fs.go
- stargz/fs_test.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
- stargz/remote/urlreaderat.go
- stargz/remote/urlreaderat_test.go
Stargz Snapshotter project is partially (mainly for filesystem and image converter) based on CRFS project which is licensed under 3-Clause BSD. We add 3-Clause BSD file header for codes originated from CRFS and add a NOTICE file. Stargz Snapshotter project is still licensed under Apache License 2.0.
> Govern codes from CRFS project by the license of the project

- .github/workflows/benchmark.yml
- Makefile
- NOTICE.md
- script/benchmark/docker-compose-benchmark.yml.sh
- script/benchmark/hello-bench/Dockerfile
- script/benchmark/hello-bench/config/config.containerd.toml
- script/benchmark/hello-bench/config/config.stargz.toml
- script/benchmark/hello-bench/prepare.sh
- script/benchmark/hello-bench/reboot_containerd.sh
- script/benchmark/hello-bench/run.sh
- script/benchmark/hello-bench/src/gcc/main.c
- script/benchmark/hello-bench/src/hello.py
- script/benchmark/tools/format.sh
- script/benchmark/tools/plot.sh
- script/benchmark/tools/table.sh
- script/make.sh
This commit enables us to measure container's startup performance with benchmark based on [HelloBench](https://github.com/Tintri/hello-bench) project.
On each opening and updating PR, we run the benchmark on the GithubAction's "ubuntu-18.04" runner and post the result as a comment. We use Docker Hub for storing legacy/stargz/extended-stargz images.
We should show the benchmarking result graphically but we don't have straightforward ways to post images as comments. Currently, we show the result as tables.
> Enable to benchmark on CI

- snapshot/snapshot.go
- stargz/fs.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
This commit enables us to prefetch layers in parallel using goroutine and fixes #37.
To make sure that prefetch completes when we "actually" use these layers(e.g. unpacking layers on it or adding a writable layer on it for the container execution) we synchronize the prefetch completion using `filesystem.Check()` as following.
- When layers are actually used, containerd queries list of mount points(`mount.Mount[]`) and at this point, we check the layer status by invoking `filesystem.Check()` for each layer. 
- The first `filesystem.Check()` of the layer waits for the prefetch completion with a reasonable timeout(10 sec).
> Prefetch layers in parallel

- stargz/fs.go
- stargz/fs_test.go
Fixes #31
This commit hides state dir(`/.stargz-snapshotter`) from getdents(2) to avoid affecting differ implementations.
```
root@32d4520a7fb5:/# ls -a /
.  ..  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@32d4520a7fb5:/# ls -a /.stargz-snapshotter
.
..
sha256:e43418d927530df8736bfc362d26997f0c96bfcf90b6fb594510d54da0d3f366.json
sha256:e5a5544b4500edc7341910013633704a3edac54ee52990ac628a5fbc5a591075.json
sha256:f05c0f4ff792f589752764487e35ce1b60eaad399353b2fce046874b1b74df3b.json
sha256:feb2e5ef2735310a4116fbe6571cbcda2640f94ed5e2305e56d1b3b1c7995f6a.json
```
In the future, we should also make the state directory read-only(or prohibit to create files in) on the container's **merged** rootfs as well. This is because once we …
> Hide state dir from ReadDir req to avoid affecting diffing result

- script/benchmark/hello-bench/Dockerfile
- script/demo/Dockerfile
- script/integration/containerd-stargz-grpc/Dockerfile
- script/integration/containerd/Dockerfile
- script/make.sh
- script/optimize/optimize/Dockerfile
- stargz/fs.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
- stargz/remote/urlreaderat.go
We can use `Clone` method for `Transport` since [golang:1.14](https://github.com/golang/go/commit/5e404b362098318b5237673ef24834ef88912caa). This allows us to safely have a separated `RoundTripper` for prefetching, which can be expected to lead to performance improvement.
> Clone RoundTripper for prefetch and background-fetch

- script/benchmark/hello-bench/src/hello.py
We are getting an error on resolving localhost address during benchmarking `glassfish:4.1-jdk8` for all type of images (all of `org`, `sgz` and `esgz`).
```
out: SEVERE: Cannot determine host name, will use localhost exclusively
out: java.net.UnknownHostException: e299678ae708: e299678ae708: unknown error
out: at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
...
```
This commit fixes it by allowing benchmarking images using the host's well-configured network namespace.
> Fix error of resolving localhost in glassfish benchmarking image

- .github/workflows/benchmark.yml
- script/make.sh
Our benchmarking CI currently shows the result by posting it as a comment on PR([example](https://github.com/containerd/stargz-snapshotter/pull/49#issuecomment-591762620)). But Github Actions [prohibit actions in forked repos to post comments to PRs](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token). For example, PR #53 from a forked repo (`ktock/stargz-snapshotter`) [fails to get benchmarking result comment from Github Actions](https://github.com/containerd/stargz-snapshotter/pull/53/checks?check_run_id=484397124).
This commit enables us to use Github Actions ["artifacts" functionality](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#abo …
> Use Github Actions artifact for benchmarking output

- .github/workflows/benchmark.yml
- script/benchmark/hello-bench/Dockerfile
- script/demo/Dockerfile
- script/integration/containerd-stargz-grpc/Dockerfile
- script/integration/containerd/Dockerfile
- script/make.sh
- script/optimize/optimize/Dockerfile
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> optimization debian package manager tweaks

- cmd/ctr-remote/sampler/sampler.go
Currently, once image optimization starts we cannot cancel it and need to wait for the completion. This commit enables us to cancel the optimization.
> Enable to cancel optimization on getting signal

- README.md
- script/demo/config.stargz.toml
- script/integration/containerd-stargz-grpc/config.toml
- script/integration/containerd-stargz-grpc/entrypoint.sh
- script/integration/containerd/entrypoint.sh
- script/integration/docker-compose-integration.yml.sh
- stargz/fs.go
- stargz/fs_test.go
- stargz/remote/blob.go
- stargz/remote/blob_test.go
- stargz/remote/resolver.go
- stargz/remote/resolver_test.go
#61
This patch enables to configure mirror registries for this snapshotter, independent to containerd.
We can configure mirror registries in our config file like:
```toml
[resolver.mirrors]
registryexample.io = ["mirrorexample.com:5000", "mirrorexample2.com:5000"]
```
Authentication is done with `~/.docker/config.json` like as before.
The patch is a bit large but what is done is relatively simple.
- Moved resolver-related codes from `/stargz/fs.go` to `/stargz/remote/...`
- Added mirror registry support to `/stargz/remote/resolver.go` and added some tests
- Renamed `URLReaderAt`(`stargz/remote/urlreaderat.go`) to `Blob` (`stargz/remote/blob.go`) because its feature became richer by some codes (authentication of `RoundTripper` and getter of the blob size info) ported from `/stargz/fs.go`.
> Support mirror registries

- .github/workflows/tests.yml
- Makefile
- script/cri/build.sh
- script/cri/test-legacy.sh
- script/cri/test-stargz.sh
- script/make.sh
- snapshot/snapshot.go
This commit adds CRI validation tests for containerd + this snapshotter using [ones provided by `kubernetes-sigs/cri-tools`](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/validation.md).
They will be applied for the following situations:
- all images used in the tests are legacy docker images
- they are stargz images (hence all snapshots will be remote snapshots)
Through the first situation, we can check the snapshoter's fallback behaviour being valid for CRI and through the second one we can check remote snapshots meets specs required by CRI.
> Add CRI validation tests for stargz snapshotter

- .github/workflows/benchmark.yml
- README.md
- docs/pre-converted-images.md
Following-up: https://github.com/containerd/stargz-snapshotter/pull/58#pullrequestreview-373316667
We started a new organization https://hub.docker.com/u/stargz on Docker Hub. Let's use this for our benchmarking. This commit includes some minor updates for docs.
> Use dedicated org on Docker Hub for pre-converted images

- cmd/ctr-remote/commands/rpull.go
- cmd/ctr-remote/sorter/sorter.go
- cmd/ctr-remote/sorter/sorter_test.go
- script/optimize/optimize/entrypoint.sh
- stargz/fs.go
- stargz/fs_test.go
- stargz/handler/handler.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
Fixes: #29
Currently, stargz snapshotter doesn't support prefetch for non-optimized stargz
images.
This commit adds a configuration value for the size to prefetch layers. We can
configure it through the config file and also can override it with snapshot
labels. Non-optimized images will be prefetched respecting the value. If
optimized images are provided, the optimized size to prefetch will be
used. During optimization, non-accessed layers are marked as "no prefetch". When
we pull these layers all the above values are disabled and no prefetch will
occur.
By default, no prefetch occur (prefetch size = 0) for non-optimized images.
TODO list:
cc: @AkihiroSuda
> Add configuration for default prefetch size

- .github/workflows/tests.yml
DCO checker [requires history](https://github.com/vbatts/git-validation/blob/656ba47bb0be8aba4934bb4b2e91863edb406c36/rules/dco/dco.go#L30-L34) for skipping check for merged commits but actions/checkout V2 [doesn't fetch history by default](https://github.com/actions/checkout#usage). As a result, DCO checks fail for merge commits which don't have signature.
> Fix actions/checkout conf to enable DCO check for merge commits

- README.md
- docs/pre-converted-images.md
- script/benchmark/hello-bench/src/hello.py
Now stargz snapshotter supports CRI and has Dockerfile for kind so brief demo for kubernetes should be valuable for kubernetes users.
> Add quick start for Kubernetes with KinD

- stargz/fs.go
- stargz/remote/blob_test.go
- stargz/remote/resolver.go
- stargz/remote/util.go
Some cloud-provided registries including GCR doesn't support multi range request (e.g. `range: bytes=0-3,5-9,16-20`)
For example, when we pull an image from GCR,
```console
fetching sha256:36d56a39... application/vnd.docker.distribution.manifest.v2+json
fetching sha256:b993a6c1... application/vnd.docker.container.image.v1+json
fetching sha256:ce77d9a4... application/vnd.docker.image.rootfs.diff.tar.gzip
fetching sha256:cc65679c... application/vnd.docker.image.rootfs.diff.tar.gzip
fetching sha256:dcc819e8... application/vnd.docker.image.rootfs.diff.tar.gzip
fetching sha256:1b677c82... application/vnd.docker.image.rootfs.diff.tar.gzip
```
We get 400 response because of multi range request.
```
DEBU[2020-04-23T02:27:15.607869311Z] failed to read layer …
```
> Use single range request for registries which don't support multi range request

- stargz/fs.go
- stargz/fs_test.go
- stargz/handler/handler.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
- stargz/remote/blob.go
Currently, resolving each layer in an image are done sequentially. But it can be done in parallel by passing all layer digests in the image to `Prepare` of this snapshotter.
This commit enables this by adding a new optional label `containerd.io/snapshot/remote/stargz.chain` for passing all digests in the target image and by resolving all digests in parallel.
> Resolve layers in parallel

- go.mod
- go.sum
- vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
- vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
- vendor/modules.txt
Notable change:
- Improving connection reusing for better performance of connecting to registries: https://github.com/google/go-containerregistry/pull/712
> Vendor google/go-containerregistry 48f605c3b60a55e8029e3ec6d98f36bd43d59a9c

- script/cri/test-stargz.sh
- script/demo/config.stargz.toml
- script/integration/containerd/config.stargz.toml
- stargz/fs.go
- stargz/remote/resolver.go
- stargz/remote/resolver_test.go
Currently, filesystem uses infinitely growing map for pooling connections, etc,
which potentially run out available memory on the system. This commit fixes this
by using finite LRU caches as these pools.
> Use finite caches for pools

- cache/cache.go
- cmd/ctr-remote/sorter/sorter.go
- cmd/ctr-remote/sorter/sorter_test.go
- script/demo/docker-compose.yml
- script/integration/test.sh
- stargz/fs.go
- stargz/fs_test.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
- stargz/remote/blob.go
- stargz/remote/blob_test.go
- stargz/remote/resolver.go
- task/task.go
Related: #88 
Recently it turned out stargz filesystem uses too much memory.
This commit improves the memory usage by the following fixes:
- Do not use bufio with huge buffer
- Make sure to close gzip Reader
- Make the default size of LRU memory cache smaller
- Avoid to loading whole prefetching regions to memory at once
- Mimimize []byte allocation and keep the scope as small as possible
measured on Ubuntu 18.04(Linux 4.15.0-62-generic).
```console
$ docker exec -it stargz-demo-control-plane  ps auxww | grep -e containerd-stargz-grpc -e MEM | grep -v grep
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       148 27.7 21.2 9871492 3428132 ?     Ssl  06:57   1:31 /usr/local/bin/containerd-stargz-grpc --log-level=debug …
```
> Improve memory usage

- cmd/containerd-stargz-grpc/main.go
- script/benchmark/hello-bench/Dockerfile
- script/benchmark/hello-bench/reboot_containerd.sh
- script/benchmark/hello-bench/run.sh
- script/cri/test-stargz.sh
- script/cri/test.sh
- script/integration/containerd/Dockerfile
- script/integration/containerd/entrypoint.sh
- script/util/utils.sh
- snapshot/snapshot.go
Currently, we have two ways to check the success of remote snapshot
preparation. Integration test checks output messages from `ctr-remote`
command. CRI test checks the log from stargz daemon. We should unify them
because we want to keep the consideration the about log messages as small as
possible.
We use the log from stargz daemon for both tests. For preventing the message
from accidentally changed, this commit defines the message as `const` value and
adds some comments.
This commit also adds this check to the benchmarking script.
> Define log message for failure of remote snapshot preparation

- script/cri/test.sh
This mitigates recent flaky in our CI; See also https://github.com/kubernetes-sigs/cri-tools/pull/618 .
> Use cri-tools version 75ef33dc2b4ecb08e0237d91de1b664909d262de

- cache/cache.go
- cache/cache_test.go
- stargz/fs.go
- stargz/fs_test.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
- stargz/remote/blob.go
- stargz/remote/blob_test.go
- stargz/remote/resolver.go
- stargz/remote/util.go
- stargz/remote/util_test.go
Throughout the benchmark on #101, it turned out the file read performance is low especially on random and parallel reads. This PR includes two patches to mitigate this problem and improve file read performance.
The first patch is for squashing HTTP Range Request header on large prefetch. Current filesystem implementation chunks the prefetching range into small, many, and mostly neighbouring chunks and lists them in a single HTTP Range Request header without enough squashing. Sometimes this leads to large HTTP header and the prefetch request fails. This commit solves this by aggressively squashing neighbouring/overwrapping chunks in HTTP headers, as much as possible.
The second one contains the following optimizations for caches:
- minimizing the occurrence of byte slice allocation in the …
> Improve file read performance

- snapshot/snapshot.go
- snapshot/snapshot_test.go
- stargz/fs.go
Our `FileSystem` implementation holds a `map[string]*layer` for tracking the
state of each stargz mountpoint. Currently, `FileSystem` interface defined in
`snapshot` package doesn't have `Unmount` API and `syscall.Unmount` is directly
called to the mountpoint. Filesystem implementation asynchronously finalizes
that `map`, which is hard to be done safely and rather race condition will possibly
occur.
This is good timing for us to add `Unmount` method to the `FileSystem` API,
which delegates the actual `unmount` task to the filesystem implementation. This
also enables the filesystem to do necessary finalization before/after the
`unmount` syscall.
> Add `Unmount` API to the FileSystem

- .github/workflows/tests.yml
- script/util/utils.sh
The latest official registry:2 docker image doesn't contain htpasswd command which is used in our CI for setting up private registries for testing.
This seems the cause of the current CI failure.
> Use htpasswd command on the system during test

- cmd/ctr-remote/commands/optimize.go
- script/optimize/optimize/Dockerfile
- script/optimize/optimize/entrypoint.sh
- stargz/verify/verify.go
- stargz/verify/verify_test.go
Related: https://github.com/containerd/stargz-snapshotter/issues/114
Current stargz image has two problems towards content validation:
- The digest of TOC JSON isn't stored in verifiable image manifests
- Content digests are stored in file granularity (not in chunk granularity)
By solving them, we can construct a chain of verification (i.e. manifest -> TOC JSON -> chunk).
This commit solves them in backwards-compatible ways as the following.
For the first one, this commit adds an annotation `containerd.io/snapshot/stargz/toc.digest` to the image manifest for storing the digest of TOC JSON.
For the second one, this commit extends the TOCEntry with an additional (and optional) field `ChunkDigest` for storing chunk-level content digest. Stargz lib chunks a large file to smaller "chunk" …
> Extend stargz for content verification

- docs/overview.md
Type of option 'insecure' is bool, not string.
> Fix variable type in config at overview.md

- .github/workflows/benchmark.yml
Though the VM spec is documented in the [Github Actions documentation](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources), we should get the concrete instance type and location used during benchmarking for reproducibility.
Output from https://github.com/ktock/stargz-snapshotter/runs/876409478:
```json
{
"location": "eastus2",
"vmSize": "Standard_DS2_v2"
}
```
In this case, we run [`Standard_DS2_v2`](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) instance in `eastus2`.
> Get instance location and type during benchmarking

- .github/workflows/benchmark.yml
- script/benchmark/hello-bench/run.sh
- script/benchmark/hello-bench/src/hello.py
- script/benchmark/test.sh
- script/benchmark/tools/csv.sh
- script/benchmark/tools/percentiles.sh
- script/benchmark/tools/util.sh
In our current benchmark, we simply show the average time to take for each operation during container startup.
This commit improves the benchmarking codes to contain the benchmarking results in more detail. This commit also includes some changes trying to improve the stability of the benchmarking results. We don't change the benchmarking method itself and is still HelloBench-based one.
- Using 95 percentiles instead of the average value.
- Containing lists of percentile values of the benchmark results.
- Not executing `sync` command explicitly during benchmarking of `pull` operation. The time to take for (implicit) disk sync will be included in operations (create, run) following the pull operation.
- For each iteration during the benchmark, randomize the order of samples execution.
> Show benchmarking result in more detail and improve the stability

- script/benchmark/hello-bench/src/hello.py
- script/demo/config.stargz.toml
- stargz/fs.go
Related: https://github.com/containerd/stargz-snapshotter/issues/114
Currently, we can bypath content verification when the image has an annotation `containerd.io/snapshot/remote/stargz.skipverify`, even if the snapshotter config doesn't allow non-verifiable images (= `allow_no_verification = false`).
This commit fixes this behaviour and tighten the restriction for non-verifiable images. Non-verifiable images can be mounted only if both of the following conditions meet:
- `allow_no_verification = true` is specified in `config.toml` of stargz snapshotter, and
- the content descriptor of the layer has an annotation `containerd.io/snapshot/remote/stargz.skipverify` (the value will be ignored).
I'm currently working on the content verification documentation and will include this restriction …
> Enable snapshotter to force content verification

- .github/workflows/tests.yml
This fixes our recent CI failure that fails to install htpasswd to the testing runners.
> Update package list before install on Github Actions runners

- snapshot/snapshot.go
- stargz/fs.go
Currently, the snapshotter checks layer sequentially but it's possible for some of the checks to wait for the prefetch completion long time and this will block the checking other layers. For avoiding this, snapshotter should check layers in parallel.
> Check layers in parallel

- stargz/fs.go
- stargz/fs_test.go
- stargz/reader/reader.go
- stargz/reader/reader_test.go
Currently, the snapshotter verifies, decompresses and caches files in a layer sequentially during prefetch and background fetch. But it's possible for some of (large) files takes long for doing so and this will block caching other files. For avoiding this, snapshotter should cache files in parallel.
> Verify and cache files in parallel

- cmd/containerd-stargz-grpc/config.go
- cmd/containerd-stargz-grpc/main.go
- stargz/config/config.go
- stargz/fs.go
- stargz/keychain/kubeconfig.go
Currently, kubeconfig-based keychain is imported to the filesystem by default
but this comes with a lot of dependencies (including `k8s.io` pkg) and this
makes importing `github.com/containerd/stargz-snapshotter/stargz` harder. Since
this commit, the filesystem doesn't import the keychain by default and the
keychain selection is configurable through the option. There is no change in
`config.toml`.
> Make keychain selection configurable

- Dockerfile
This commit adds an all-in-one image enables users having docker accessibility
to use `ctr-remote images optimize` command without installing additional
dependencies.
```console
$ docker build --target oind -t optimize .
$ docker run --rm --privileged --device=/dev/fuse --tmpfs=/tmp:exec,mode=777 \
-v ~/.docker/config.json:/root/.docker/config.json:ro \
optimize --args='[ "echo", "hello" ]' ubuntu:20.04 ktokunaga/ubs:1
time="2020-09-08T14:41:17Z" level=info msg="unpacked sha256:b66c17bbf772fa072c280b10fe87bc999420042b5fce5b111db38b4fe7c40b49"
time="2020-09-08T14:41:18Z" level=info msg="unpacked sha256:f7bfea53ad120b47cea5488f0b8331e737a97b33003517b0bd05e83925b578f0"
time="2020-09-08T14:41:18Z" level=info msg="unpacked sha256:46d371e02073acecf750a166495a63358517af793de739a51b680c973fae8fb9" …
```
> Enable to use optimize command in Docker

- script/cri/test-stargz.sh
- script/demo/docker-compose.yml
- script/integration/test.sh
This fixes recent CI failure:
```
The Compose file '/tmp/tmp.JysBvRZ2An' is invalid because:
services.testenv_integration.volumes contains unsupported option: 'nosuid'
services.testenv_integration.volumes contains unsupported option: 'nosuid'
services.testenv_integration.volumes contains unsupported option: 'nosuid'
```
> Refactor and fix docker compose file

- docs/overview.md
- stargz/config/config.go
- stargz/fs.go
Simple enhancement described in https://github.com/containerd/stargz-snapshotter/issues/145: lazy pulling can be disabled by setting `nolazypull = true` in _config.toml_.
I tested this option by executing `cat /.stargz-snapshotter/*` inside container - when it is enabled, then _fetchedSize_ is not growing up.
> Allow to disable pulling layers in background

- cmd/containerd-stargz-grpc/main.go
- snapshot/snapshot.go
- snapshot/snapshot_test.go
I found that restarting the stargz-snapshot service will cause the previous data to be unavailable.
1.  pull image
```
[root@F24core-2 lib]# ctr-remote i rpull --plain-http  192.168.120.238:5000/busybox:stargz
fetching sha256:822b941c... application/vnd.docker.distribution.manifest.v2+json
fetching sha256:0f5d3ed6... application/vnd.docker.container.image.v1+json
```
2. run container
```
[root@F24core-2 lib]# ctr-remote run  --snapshotter=stargz -t --rm 192.168.120.238:5000/busybox:stargz test hostname
F24core-2
```
3. restart stargz-snapshotter service
`[root@F24core-2 lib]# systemctl restart stargz-snapshotter`
4. run the container again
```
[root@F24core-2 lib]# ctr-remote run  --snapshotter=stargz -t --rm 192.168.120.238:5000/busybox:stargz test hostname
ctr: failed to stat parent: …
```
> fix remote snapshot is unavailable after service restart

- cmd/containerd-stargz-grpc/config.go
- cmd/containerd-stargz-grpc/main.go
- stargz/config/config.go
- stargz/fs.go
- stargz/fs_test.go
- stargz/remote/blob.go
- stargz/remote/resolver.go
- stargz/remote/resolver_test.go
#149
https://github.com/moby/buildkit/pull/1666#discussion_r489907766
Currently, registry logic of stargz snapshotter is separated from containerd and is implemented in an incompatible way with other containerd-based tools (including buildkit which uses containerd's docker.RegistryHost). This makes it hard to integrate the logic with these tools.
This commit refactors registry logic based on containerd's docker.RegistryHost. This enables the client of stargz.FileSystem to configure docker.RegistryHost based on the client-side configuration. This will make the integration of the registry logic with other containerd-based tools easier.
[This buildkit branch](https://github.com/ktock/buildkit/commit/71a5c3198792b3ab5cee3b27cb7e1572773a0514) experimentally integrates buildkitd and …
> containerd's RegistryHost-based registry logic

- stargz/reader/reader.go
#156
Currently `reader.Cache()` creates goroutines for each file contained in the
layer. This can lead to too many goroutines and possibly consume too much
resource.
This commit fixes it by limiting the number of goroutines using semaphore.
cc: @strigazi
> Avoid launching too many goroutines during caching layer

- snapshot/snapshot.go
- snapshot/snapshot_test.go
- stargz/fs.go
- stargz/fs_test.go
- stargz/remote/blob.go
- stargz/remote/resolver.go
Following-up: #149 #153
Related: moby/buildkit#1666 (comment)
Currently, if connectivity check on a layer fails during `FileSystem.Check` API,
the registry configuration(docker.RegistryHost) of that layer is refreshed based
on initially (during `FileSystem.Mount`) provided snapshot labels. But that
configuration should be refreshed using the *latest* labels stored in the
snapshot.
This enables snapshotter clients to update registry-configuration-related labels
through `snapshot.Update` API and the filesystem can use these labels on
refreshing the configuration.
> Enable to refresh registry configuration using the latest labels

- script/demo/docker-compose.yml
When behind a proxy, we need proxy env variables
for the build stage.
Signed-off-by: Spyros Trigazis <spyridon.trigazis@cern.ch>
> demo/compose: Add proxy config for build

- stargz/fs.go
Currently we use `time.Time.UnixNano()` (unix time in nanoseconds https://golang.org/pkg/time/#Time.UnixNano) value for `(github.com/hanwen/go-fuse/fuse).Attr.Mtimensec` but [the filed requires `time.Time.Nanosecond()`](https://github.com/hanwen/go-fuse/blob/730713460d4fc41afdc2533bd37ff60c94c0c586/fuse/attr.go#L40) which is the nanosecond *offset* within the second specified by that time https://golang.org/pkg/time/#Time.Nanosecond . This difference leads to wrong calculation of mtime of that file as the following:
On overlayfs snapshotter:
```console
1551367831.000000000
```
On stargz-snapshotter:
```console
1551367831.-1564924416
```
This commit fixes this issue by using the method provided by the go-fuse lib for setting times.
> Fix wrong mtime calculation

- stargz/remote/blob.go
- stargz/remote/resolver.go
Related: https://github.com/containerd/stargz-snapshotter/issues/155
ghcr.io (recently?) uses s3 backend (`https://github-production-container-registry.s3.amazonaws.com`) for distributing layer blobs. But currently we are facing the following problems when lazypulling from that registry.
- The backend doesn't allow HEAD request : fails with 403 (seems related to #128 where HEAD from `docker-images-prod.s3.amazonaws.com` fails)
- The redirected URL (`https://github-production-container-registry.s3.amazonaws.com/blobs...`) expires soon (300sec?) : fails with 403
Reproducer for the HEAD issue:
```console
$ curl -v https://ghcr.io/token?scope=repository:stargz-containers/python:pull
... getting token here ....
$ curl -v -H "Authorization: ..." …
```
> Enable to pull from ghcr.io

- .github/workflows/benchmark.yml
- README.md
- docs/pre-converted-images.md
- script/benchmark/hello-bench/prepare.sh
- script/benchmark/hello-bench/run.sh
- script/benchmark/hello-bench/src/hello.py
- script/benchmark/test.sh
- stargz/remote/resolver.go
Fixes: #155
This commit uses pre-converted images stored on ghcr.io in our Github Actions
jobs. This also updates some docs in this repo to use images on ghcr.io.
> Use pre-converted images on ghcr.io

- cmd/ctr-remote/commands/optimize.go
- cmd/ctr-remote/sampler/options.go
- cmd/ctr-remote/sampler/sampler.go
Related: #169
Currently, `ctr-remote i optimize` doesn't set runc's mount configration.
This commit add a new option for enabling to pass mount config to runc.
The syntax of this option is compatible to containerd's ctr command.
```console
WARN[0000] 2020/11/10 09:49:51 No matching credentials were found, falling back on anonymous 
INFO[0004] unpacked sha256:04a987509d1e5d70dbfe6aad61f2ee3d70a512c0f3434723639b70b24d072c0d 
INFO[0006] unpacked sha256:2b7dda57fc554194146e95280cdd43f06eb365fe7e899fb3e72ceed98830a9bf 
INFO[0008] unpacked sha256:652b54dc0d9a7defffa4164e74b17f290c50a24138bb10b99cd37b042790dce2 
INFO[0010] unpacked sha256:52dc0ed31371840fb6adae9a4c0cfc7b04a047ee55ee17b90e2fbe24f05eac97 
INFO[0011] unpacked sha256:02f29fcc3f22186a0f62a6b7f171d8e851191ad902b3d57622137b501f53b041 …
```
> Enable to pass mount config to runc during optimize

- cmd/ctr-remote/commands/optimize.go
Related: #169
Currently, `ctr-remote i optimize` always converts all layers including already
optimized eStargz layers. However, sometimes we want to *reuse* these optimized
layers for saving resources consumed for these conversion.
This commit adds an option which enables to reuse already optimized eStargz
layers without conversion. With this option, a layer is reused when it is a
valid eStargz and no access occur to that layer during runing the workload.
In the future, we should remotely mount and lazily pull these eStargz layers
instead of downloading.
```console
ond
WARN[0000] 2020/11/10 15:57:49 No matching credentials were found, falling back on anonymous 
INFO[0000] unpacked                                      digest="sha256:04a987509d1e5d70dbfe6aad61f2ee3d70a512c0f3434723639b70b24 …
```
> Enable to reuse already optimized layers without conversion

- cmd/ctr-remote/builder/build.go
- cmd/ctr-remote/builder/build_test.go
- cmd/ctr-remote/commands/optimize.go
- cmd/ctr-remote/sorter/sorter.go
- cmd/ctr-remote/sorter/sorter_test.go
Related: #169 
This commit parallelize building stargz blob into several goroutines. The number
of goroutines is currently at least the number of the
`runtime.GOMAXPROCS(0)`.
In this patch, during building a stargz blob, the original tar archive is divided into several
parts. These parts are converted to stargz in parallel. Finally, the converted
(parts of) stargz blobs are combined into one blob.
Converting `ghcr.io/stargz-containers/fedora:30-org` into eStargz on Github Actions.
https://github.com/ktock/stargz-snapshotter/actions/runs/366409761
```console
ctr-remote i optimize --args='[ "echo", "hello" ]' \
--plain-http ghcr.io/stargz-containers/fedora:30-org http://registry-ctr2:5000/fedora:30-esgz
```
Measured 3 times:
```
real	0m54.206s
user	0m56.162s
sys	0m1.495s
real	0m54.850s
user …
```
> Parallelize building stargz blob

- cmd/ctr-remote/commands/optimize.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/README.md
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/blob.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/doc.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/image.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/index.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/layoutpath.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/options.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/read.go
- vendor/github.com/google/go-containerregistry/pkg/v1/layout/write.go
- vendor/modules.txt
Currently, ctr-remote only converts images matching to the platform it running
on.
This commit allows ctr-remote to handle image index and convert images of all or
a specific platform. Based on the ability of handling index, this commit also
enables to input/output imgaes from/to the local filesystem following OCI Image
Layout.
```console
WARN[0000] 2020/11/22 10:02:57 No matching credentials were found, falling back on anonymous 
INFO[0005] unpacked                                      digest="sha256:9d48c3bd43c520dc2784e868a780e976b207cbf493eaff8c6596eb871cbd9609" platform=linux/amd64
INFO[0005] running container "but3elopt0h6tb9qo4bg"      platform=linux/amd64
hello
INFO[0006] container "but3elopt0h6tb9qo4bg" stopped      platform=linux/amd64
INFO[0006] cleaned up successfully …
```
> Enable ctr-remote to handle image index

- .github/workflows/release.yml
- Dockerfile
This commit adds a Github Actions workflow to automatically create a draft
release with binaries, triggered by pushing a tag.
> Add release workflow to Github Actions

- estargz/build.go
- estargz/build_test.go
Currently, during optimization, if a hardlink is specified as a prioritized
file, the target file isn't included to prioritized file but only the hardlink
entry is moved forward in the tar file. However, some tar client (e.g. GNU tar)
don't allow that the hardlink entry comes forwarder than the target entry.
> Ensure hardlink target entry comes forwarder than the source entry

- script/benchmark/config/config.cni.conflist
- script/benchmark/hello-bench/src/hello.py
- script/benchmark/test.sh
Recently, we added mount & NW support for `ctr-remote` (https://github.com/containerd/stargz-snapshotter/blob/master/docs/ctr-remote.md). Let's enable these functionality for creating pre-converted images used in the benchmark.
> Update benchmark preparation script to use mount and NW

- script/benchmark/config/config.stargz.toml
- script/benchmark/hello-bench/run.sh
- script/benchmark/hello-bench/src/hello.py
- script/benchmark/tools/csv.sh
- script/benchmark/tools/percentiles.sh
- script/benchmark/tools/plot.sh
- script/benchmark/tools/table.sh
Related: #184
This fixes benchmarking scripts for using eStargz (without optization) instead
of stargz. The non-optimized images are built by `--no-optimize` option of
`ctr-remote image optimize`.
From: https://github.com/ktock/stargz-snapshotter/actions/runs/398452630
> Fix benchmark to use non-optimized eStargz instead of stargz

- script/integration/containerd/entrypoint.sh
- snapshot/snapshot.go
#187
Currently, when `Prepare()` fails to prepare a remote snapshot, it falls back to
the normal overlayfs mode even after the remote snapshot is mounted on this
snapshot directory by `FileSystem.Mount()`.
Here, we shouldn't keep using this already-mounted snapshot (calls *WIP
snapshot* here) and we are recently seeing errors related to this. When the
client tries to `Prepare` the same `ChainID`'s remote snapshot from different
namespaces, the second `Prepare()` fails on `commit()` with `AlreadyExists`
error. Currenlty, this returns the WIP snapshot to the client. When the client
tries to unpack the layer on this WIP snapshot (following the normal snapshot
preparation procedure), it fails because the mounted (read-only) snapshot
doesn't allow to write there.
Note that this bug doesn't …
> Don't allow the client to keep using WIP snapshot on `Prepare()` failure

- cmd/ctr-remote/commands/optimize.go
- cmd/ctr-remote/sampler/options.go
- cmd/ctr-remote/sampler/sampler.go
So I want to run the container a bit longer until it finishes all the
work for optimization. This option allows the container to wait until a
keyboard signal (`Ctrl-C`) or a signal from other programs.
Added this option to `ctr-remote i optimize` command:
```
--wait-on-signal             ignore context cancel and keep the container running until it receives signal (Ctrl + C) sent manually
```
Signed-off-by: Jun Lin Chen webmaster@mc256.com
> Add an option to ignore context canceled.

- cmd/ctr-remote/commands/optimize.go
- converter/converter.go
- converter/optimizer/optimizer.go
The flag is a converter concept and should not be in the optimizer package.
> converter: move NoOptimize flag from optimizer to converter

- docs/stargz-estargz.md
- estargz/build.go
- estargz/build_test.go
- estargz/estargz.go
- estargz/estargz_test.go
#200
https://github.com/kubernetes-sigs/kind/issues/1981
This enables estargz lib client to specify compression level of gzip lib by adding a new option `WithCompressionLevel`.
According to eStargz spec, footer must be 51 bytes so footer's compression level must not be configurable (i.e. gzip.NoCompression).
> Enable to pass compression level to gzip lib

- converter/converter.go
- converter/optimizer/layerconverter/layerconverter.go
- estargz/build.go
- estargz/build_test.go
- estargz/estargz.go
- fs/fs_test.go
- fs/reader/reader_test.go
#203
This moves  prioritized files argument to option.
There are cases where input tar entiy names are prefixed with "./" (which is
still valid) but we shouldn't expose this difference in the option.
So this commit also adds a simple normalization (trimming "./" prefix).
> Move prioritized files argument to option

- estargz/build.go
- estargz/errorutil/errors.go
- estargz/errorutil/errors_test.go
- estargz/estargz.go
- estargz/go.mod
- estargz/go.sum
This lets functions that want to aggregate and return a collection of errors use a `[]error` to accumulate them, and `errorutil.Aggregate(list)` to turn them into a single `error`.  If the list is empty, the `error` will be nil.  If the list is a singleton, it will return the single error.  Otherwise, it will construct a new error combining the constituent error messages.
Fixes: https://github.com/containerd/stargz-snapshotter/issues/205
> Replace the multierror dependency with a simple error aggregator.

- converter/converter.go
- converter/optimizer/layerconverter/layerconverter.go
- estargz/build.go
- estargz/build_test.go
- fs/fs_test.go
- fs/reader/reader_test.go
#204
This commit enables to get uncompressed digest (DiffID) from built eStargz by
introducing `DiffID` method to the result ReadCloser.
> estargz: Enable to get uncompressed digest (DiffID) from built eStargz

- converter/optimizer/logger/logger_test.go
This test requires root for FUSE-related operation. We should move it to
`-test.root` for make `make test` succeed for non-root users.
(`make test-all` still requires root but can run all tests including `-test.root`)
> Move TestOpenRead to `-test.root`

- docs/verification.md
- estargz/types.go
The annotation should be considered valid only when it is specified as a layer annotation.
> docs: clarify the location of TOC digest annotation

- estargz/build.go
- estargz/build_test.go
https://github.com/google/go-containerregistry/pull/879#issuecomment-748398008
Currently, even if a path specified in the prioritized files list isn't found in
the tar archive, no error is propagated. But this possibly result in the eStargz
file unexpected by the client so we should propagate this error to the client.
cc @AkihiroSuda @mattmoor
> Propagate not-found error during sort

- cmd/containerd-stargz-grpc/main.go
resolve https://github.com/containerd/stargz-snapshotter/issues/97
In addition to `script/integration/containerd/entrypoint.sh`, I found `--config=/etc/containerd-stargz-grpc/config.toml` hardcoded in several other files.
However, I thought it would be better to make them explicit in some cases, so I have not removed all of them.
Signed-off-by: Nozomu Ohki <nozomunoise@gmail.com>
> Add defaultConfigPath

- estargz/build.go
- estargz/build_test.go
https://github.com/google/go-containerregistry/pull/879#issuecomment-748398008
Since this commit, WithPrioritiedFiles option accepts "/"-prefixed prioritied
files. It's also accepted that file entreis in the input tar are prefixed by
"./" or "/".
This should be merged after #212 is merged and conflicts are resolved.
cc @AkihiroSuda @mattmoor
> Support "/"-prefixed prioritized files

- estargz/build.go
- estargz/build_test.go
https://github.com/containerd/stargz-snapshotter/issues/217#issuecomment-748710444
`estargz.Build` currently doesn't support duplicated entries in the input tar.
But there are images that contain duplicated entries in a layer and we currently
cannot optimize these layers.
GNU tar supports duplicated entries by replacing the former entry with the later
one. (https://www.gnu.org/software/tar/manual/html_node/multiple.html) This
commit takes the simillar approach for supporting duplicated entries.
> estargz: Support duplicated entries during sort

- estargz/build.go
- estargz/build_test.go
https://github.com/containerd/stargz-snapshotter/pull/212#issuecomment-748483624
This commit adds a new option WithAllowPrioritizeNotFound. This makes Build
continue the execution even if some of prioritized files specified by
WithPrioritizedFiles option aren't found in the input tar. Instead, this records
all missed file names to the passed slice.
> Allow some of prioritized files are missed during sort

- estargz/estargz.go
- estargz/estargz_test.go
- fs/reader/reader.go
#220
Currently, estargz lib makes an infinite reference loop of TOCEntry when the
input estargz contains the entry of the root directory itself. As a result, the
client walks infinite TOCEntry tree. This commit fixes this issue and adds a
test to detect it. This commit also adds a logic to prevent the infinite
recursive call of `cacheWithReader`.
> estargz: avoid infinite loop of reference of entries

- estargz/build.go
- estargz/build_test.go
- estargz/estargz.go
- estargz/estargz_test.go
https://github.com/containerd/stargz-snapshotter/issues/217#issuecomment-748710444
Currently, when estargz lib reads an eStargz, it normalizes the entry by
trimming the prefix "./".
But this isn't enough because there are a lot of exceptions including
"/foo/bar", "../foo/bar", etc. From the library client's perspective
(e.g. snapshotter), it's complex to take care of all these differences when
interacting with unmarshaled eStargz blob with `estargz.Reader`.
For example, when the client gets a TOCEntry from `estargz.Reader.Lookup(path
string)`, it needs to prefix the path to be lexically equal to the corresponding
tar entry (so it needs to prefix that path with "/" if the corresponding tar
entry is prefixed by "/"). Additionally, when the client gets a TOCEntry
(e.g. by …
> estargz: Clean entry names when read and unmarshal blob

- fs/config/config.go
- fs/remote/blob.go
- fs/remote/blob_test.go
- fs/remote/resolver.go
Resolves: #226
Currently, the timeout for fethcing chunks is 30s but this is too short on some
environments.
This commit make this configurable on `config.toml` (with `fetching_timeout`
option) and extended the default timeout (300s).
cc: @mattmoor
> Make timeout for fetching chunks configurable

- cmd/ctr-remote/commands/optimize.go
- converter/converter.go
- converter/optimizer/optimizer.go
- converter/optimizer/recorder/recorder.go
Now `ctr-remote image optimize` accepts `--record-out=<FILE>` flag.
This flag dumps the monitor log to a line-deliminated text file.
e.g.,
```json
{"path":"etc/passwd","manifestDigest":"sha256:02f6b131fbb5a7438e4d5bf8a06317b746c91c8e9d5a75be4d3cec8b69ae498a","layerIndex":0}
{"path":"etc/group","manifestDigest":"sha256:02f6b131fbb5a7438e4d5bf8a06317b746c91c8e9d5a75be4d3cec8b69ae498a","layerIndex":0}
{"path":"etc/passwd","manifestDigest":"sha256:02f6b131fbb5a7438e4d5bf8a06317b746c91c8e9d5a75be4d3cec8b69ae498a","layerIndex":0}
{"path":"etc/group","manifestDigest":"sha256:02f6b131fbb5a7438e4d5bf8a06317b746c91c8e9d5a75be4d3cec8b69ae498a","layerIndex":0}
{"path":"usr/lib64/ld-2.28.so","manifestDigest":"sha256:02f6b131fbb5a7438e4d5bf8a06317b746c91c8e9d5a75be4d3cec8b69ae498a","layerIndex":0} …
```
> optimize: allow dumping monitor log to a file

- cmd/ctr-remote/commands/convert.go
- cmd/ctr-remote/main.go
- nativeconverter/estargz/estargz.go
- nativeconverter/nativeconverter.go
- nativeconverter/uncompress/uncompress.go
The `nativeconverter` package provides containerd-native converter that does not depend on GGCR.
Usage: `ctr images convert --oci --estargz SRC DST`
Specifying `--oci` is highly recommended, otherwise "containerd.io/snapshot/stargz/toc.digest" will be lost, unless the original image has already OCI mediatype.
Close #223
> containerd-native converter

- Dockerfile
Fixes https://github.com/containerd/stargz-snapshotter/issues/231
> Add default value and docs for TARGETARCH

- nativeconverter/estargz/estargz.go
- nativeconverter/estargz/estargz_test.go
- nativeconverter/nativeconverter.go
- util/testutil/testutil.go
blobs without `containerd.io/uncompressed` labels were not supported
> nativeconverter.GetDiffID: support non-unpacked blobs + fix nil panic + add test

- fs/config/config.go
- fs/fs.go
Increasing the number of concurrent background tasks (connections) may speed up the loading speed if the network condition is good. I propose to add a parameter to adjust the number of concurrent background tasks.
Signed-off-by: Jun Lin Chen <webmaster@mc256.com>
> Add MaximumConcurrency to config.toml (for stargz-grpc)

- cmd/containerd-stargz-grpc/keychain/dockerconfig.go
- cmd/containerd-stargz-grpc/keychain/kubeconfig.go
- cmd/containerd-stargz-grpc/main.go
We currently wrap `kubeconfig` keychain with ggcr and we use ggcr for getting
creds from `~/.docker/config.json`. Initially this was right because the
filesystem's auth logic was entiery based on ggcr.
But we refactored auth logic based on based on containerd's registry lib so it's
good time for us to refactor keychain without depending on ggcr as well.
> Refactor keychain

- fs/fs.go
Currently, `*node.Readdir` returns directory entries in undeterministic order
*on each call*. Though the order of directory entries is up to the filesystem
implementation, undeterministic order *on each call* results in that the
filesystem clients see random file name on each call of `getdents` even to the
same seek position in that directory. This commit fixes this issue by sorting
the directory entries by the name.
repro:
```golang
package main
import (
"fmt"
"os"
"syscall"
)
func printEntry(f *os.File, position int64) error {
if _, err := syscall.Seek(int(f.Fd()), position, 0); err != nil {
return err
}
buf := make([]byte, 1024)
if _, err := syscall.Getdents(int(f.Fd()), buf); err != nil {
return err
}
names := make([]string, 0, 1)
_, c, newnames := syscall.ParseDirent(buf, 1, names) …
```
> Make the order of directory entries deterministic

- Dockerfile
- cmd/containerd-stargz-grpc/main.go
- go.mod
- script/cri/test.sh
- script/optimize/optimize/Dockerfile
- script/pullsecrets/test.sh
- script/util/make.sh
Fixes #202 
When the snapshotter is compiled with especially the recent version of go, we
sometimes (or frequently) see that go-fuse prints `Write/Writev failed` log.
Here, I quote the log with few lines of debug logs around it.
```
2021/01/19 14:09:43 rx 76: FLUSH n2 {Fh 1}
2021/01/19 14:09:43 tx 76:     OK
...
2021/01/19 14:09:43 rx 77: INTERRUPT n0 {ix 76}
2021/01/19 14:09:43 tx 77:     11=resource temporarily unavailable
2021/01/19 14:09:43 writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT
```
This warning comes when the filesystem tries to write the response to INTERRUPT
(EAGAIN, in this case) to the kernel [1].
When a filesystem operation of the client from userspace (`76: FLUSH`, in this
case) is interrupted by a signal, INTERRUPT request (`77: …
> Bump go to 1.15

- nativeconverter/estargz/estargz.go
- nativeconverter/uncompress/uncompress.go
`nativeconverter` doesn't support to resume conversion after the previous
conversion is stopped by a signal, etc.
```console
ctr-remote image convert --oci --estargz ghcr.io/stargz-containers/python:3.7-org dummy:1
C-c
ctr-remote image convert --oci --estargz ghcr.io/stargz-containers/python:3.7-org dummy:2
ctr: commit failed: "convert-estargz-from-sha256:5f37a0a41b6b03489dd7de0aa2a79e369fd8b219bbc36b52f3f9790dc128e74b" failed size validation: 16739617 != 10049153: failed precondition
```
This commit fixes this.
> nativeconverter: Enable to resume conversion

- .github/workflows/benchmark.yml
- docs/pre-converted-images.md
- script/benchmark/hello-bench/src/hello.py
`glassfish` image is officially deprecated on DockerHub and some images used in
our benchmarking are old. This commit replaces and upgrades these images.
- `glassfish:4.1-jdk8` -> `tomcat:10.0.0-jdk15-openjdk-buster`
- `glassfish` is deprecated.
- `rethinkdb:2.3.6` -> `postgres:13.1`
- The latest `rethinkdb` is too small.
- `python:3.7` -> `python:3.9`
- `gcc:9.2.0` -> `gcc:10.2.0`
> Update images used in benchmarking

- Makefile
https://github.com/containerd/stargz-snapshotter/issues/253
This reduces the binary size about 12MB (`45313893 B -> 32542720 B`).
> Strip go binary by default

- script/integration/containerd/entrypoint.sh
Recently `Integration` test is flaky and sometimes fails with the following error:
```
failed to prepare extraction snapshot "extract-888733096-M1HL sha256:645c926ab234a37fce3b0d3f9de28718b25fdfe19537e6f58c01e25561116ccf": connection error: desc = "transport: Error while dialing dial unix /run/containerd-stargz-grpc/containerd-stargz-grpc.sock: connect: connection refused": unavailable
```
This seems because tests sometimes access to stargz snapshotter before it becomes up-and-running.
This commit fixes this issue.
> Make sure the snapshotter is up-and-running during test

- README.md
- go.mod
#259
This commit eliminates the need of specifying `replace` directive in the
consumer project's go.mod.
Currently, our tests and releases are done against stargz snapshotter that
imports the local (i.e. the same commit of) `estargz` library.
```
replace github.com/containerd/stargz-snapshotter/estargz => ./estargz
```
Here, we don't want to force consumer projects (and their all downstream
projects) to specify `replace` directive but `require` directive doesn't support
to specify the local directory.
For solving this issue, this commit let the consumers manually specify the
version of `github.com/containerd/stargz-snapshotter/estargz` to the same commit
as `github.com/containerd/stargz-snapshotter` in their go.mod as an [indirect …
> [RFC] Bump estargz lib to a vaild oldest version

- Makefile
- cmd/containerd-stargz-grpc/main.go
- version/version.go
Fixes:   #268
```console
containerd-stargz-grpc v0.4.1-3-ge550b6e e550b6ea86467949c0aaa372b88f04d173afc269
```
> Add --version option to `containerd-stargz-grpc`

- cmd/containerd-stargz-grpc/main.go
- fs/config/config.go
- fs/fs.go
- fs/metrics/layer.go
- fs/metrics/metrics.go
- go.mod
- go.sum
- script/demo/config.stargz.toml
Fixes:  #271
This commit adds a metrics endpoint for exporting some useful data generated by the snapshotter.
They can be pulled by prometheus.
This commit exports the following data generated by each layer of the filesystem.
We can add more metrics if needed.
- `stargz_fs_layer_size_bytes` (counter) : The size of the layer in bytes
- `stargz_fs_layer_fetched_size_bytes` (counter) : The size of the fetched data of the layer in bytes
Each metric is labeled by the following information to distinguish each other.
- `digest` : digest of the layer
- `mountpoint` : mountpoint where the layer is mounted
Specify the arbitrary address to export metrics by configuring `/etc/containerd-stargz-grpc/config.toml`.
```toml
metrics_address = "127.0.0.1:8234"
```
The metrics can get via `/metrics` API of …
> Support exporting metrics from `containerd-stargz-grpc`

- go.mod
This release comes with enabling stargz snapshotter to be `import`-ed as a builtin plugin, supporting exporting prometheus metrics and rootless support for Ubuntu, Debian and any distro newer than Linux 5.11. For rootless setup, please refer to https://github.com/containerd/nerdctl/blob/master/docs/rootless.md.
- **Stargz Snapshotter**
- Support importing stargz snapshotter as a builtin plugin (https://github.com/containerd/stargz-snapshotter/pull/267)
- Support exporting prometheus metrics (https://github.com/containerd/stargz-snapshotter/pull/288)
- Support rootless on Linux > 5.11 (support for `userxattr` overlayfs option) (https://github.com/containerd/stargz-snapshotter/pull/290), thanks @AkihiroSuda
- Add check if snapshotter is supported during starting up of the plugin …
> Preparation for v0.5.0

- cache/cache.go
- cache/cache_test.go
- fs/layer/layer_test.go
- fs/reader/reader.go
- fs/reader/reader_test.go
- fs/remote/blob.go
- fs/remote/blob_test.go
- fs/remote/resolver.go
Though we currently use `bytes.Buffer`s in many places around the cache, some of these uses seem to be able to reduce.
This commit reduces the use of buffers around the cache, which leads to reduce memory usage of `containerd-stargz-grpc`.
We are currently using buffer during `cache.Add()` but we can reduce it by providing direct access to `*os.File` of each cache file to the cache client.
https://github.com/containerd/stargz-snapshotter/blob/17b648dd9cd4a4b859762c07b85d302e166c3387/cache/cache.go#L226-L229
This commit modifies the interface to provide the writer of that file directly to the client when adding contents to the cache.
```golang
type BlobCache interface {
Add(key string, opts ...Option) (Writer, error)
// omit...
}
```
```golang
type Writer interface {
io.WriteCloser …
```
> Reduce the use of unnecessary buffers around cache

- script/cri/test-stargz.sh
- script/cri/test.sh
Recent CRI test flakiness has been fixed in https://github.com/kubernetes-sigs/cri-tools/pull/733.
> Bump cri-tools to the latest commit and fix CRI test flakiness

- docs/pre-converted-images.md
- script/benchmark/hello-bench/src/hello.py
@AkihiroSuda Sorry for the late PR.
Resolves: https://github.com/containerd/stargz-snapshotter/issues/298
- `mariadb:10.5`: https://github.com/orgs/stargz-containers/packages/container/package/mariadb
- `wordpress:5.7`: https://github.com/orgs/stargz-containers/packages/container/package/wordpress
eStargz images are optimized against daemon startup. This will hopefully improve startup performance.
> Add mariadb:10.5 and wordpress:5.7 to ghcr.io/stargz-containers

- cache/cache.go
- fs/fs.go
- fs/fs_test.go
- fs/layer/layer.go
- fs/layer/layer_test.go
- fs/reader/reader.go
- fs/remote/blob.go
- fs/remote/resolver.go
Resolves: #308
Related: #276
Currently, content caches (`/var/lib/containerd-stargz-grpc/stargz/fscache` and `/var/lib/containerd-stargz-grpc/stargz/httpcache`) aren't cleaned up on FileSystem.Unmount().
This commit adds this functionality.
From this commit, content caches are namespaced per layer with unique ID (e.g. `/var/lib/containerd-stargz-grpc/stargz/fscache/123456` for layer A and `/var/lib/containerd-stargz-grpc/stargz/fscache/987654` for layer B).
This commit allows snapshotter to cleanup a namespace of cache when the corresponding layer is no longer referenced (i.e. unmounted).
- `resolve_result_entry = 3`  : at most 3 resolved layers are cached
```
ctr-remote i rpull ghcr.io/stargz-containers/python:3.9-esgz
```
```
ls -al /var/lib/containerd-stargz-grpc/snapshotter/snapshots …
```
> Enable to cleaning up cache on unmount

- README.md
- docs/INSTALL.md
There is systemd service config, but lacks of deployment document. 
I suggest that we can write a document to describe how to deploy stargz-snapshotter on different platforms such as Systemd, Kubernetes, AWS
> add doc for deploy with systemd

- Dockerfile
- docs/INSTALL.md
- go.mod
Since this release, lazy pulling of eStargz is possible on CRI-O/Podman using the brand-new Stargz Store plugin. Please refer to [our docs for details about installation](https://github.com/containerd/stargz-snapshotter/blob/v0.6.0/docs/INSTALL.md).
This release also adds changes for better resource efficiency of Stargz Snapshotter, including garbage collection of content cache (#309) and memory consumption improvement (#294).
- **Stargz Store**
- Add Stargz Store for enabling lazy pulling on CRI-O/Podman (#301)
- **Stargz Snapshotter**
- Add GC when unmounting snapshots (#309)
- Improve memory consumption (#294)
- Add `request_timeout_sec` option for making request timeout configurable in slow NW (#317)
- **estargz library**
- Add support of compressed input blobs to `estargz.Build` …
> Preparation for v0.6.0

- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
- github.com/coreos/go-systemd/v22 v22.3.1 -> v22.3.2
- https://github.com/coreos/go-systemd/compare/v22.3.1...v22.3.2
- github.com/klauspost/compress v1.12.2 -> v1.12.3
- https://github.com/klauspost/compress/compare/v1.12.2...v1.12.3
> Bump dependencies

- go.mod
This release enables Podman + Stargz Store (`stargz-store`) to export (`podman save`/`podman push`) lazily pulled eStargz images (#322 and https://github.com/containers/storage/pull/902). Podman need to be newer than https://github.com/containers/podman/commit/568e911b84a0a3d2e457cebdc291fea4fea44aed.
**This change only affects to Stargz Store and doesn't affect Stargz Snapshotter.**
For using this feature, each layer descriptor in the manifest of the eStargz image must have the following OCI Annotation.
- `io.containers.estargz.uncompressed-size` : contains the uncompressed size of the layer.
Our `nativeconverter` and `ctr-remote` appends this label by default since this release.
Note that this change to eStargz is backward-compatible so you can lazily pull this eStargz image still on …
> Prepare for v0.6.2

- go.mod
This version contains refactoring for builtin-mode of Stargz Snapshotter (#331).
`fusermount` is no longer needed to run Stargz Snapshotter and Starz Store.
> Prepare for v0.6.3

- go.mod
This release contains refactoring of dependencies to enable `nativeconverter` to built on windows (#333 ).
> Prepare for v0.6.4

- go.mod
- go.sum
full diff: https://github.com/docker/docker-credential-helpers/compare/v0.6.3...v0.6.4
- cli: https://github.com/docker/cli/compare/v20.10.6...v20.10.7
- docker: https://github.com/docker/docker/compare/v20.10.6...v20.10.7
> go.mod: update docker credential helpers v0.6.4, docker + cli v20.10.7

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
Fixes `go mod tidy: go.mod file indicates go 1.16, but maximum supported version is 1.15` in Project Checks action.
> Specify Go version in "Project Checks" CI

- docs/stargz-estargz.md
Looks like "Fetch Blob Part" was moved to `detail.md`
https://github.com/opencontainers/distribution-spec/commit/c90b0f145ac6bc09d2636ee214486ac333edc284#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545
> Fix a link of OCI Distribution Spec

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- MAINTAINERS
- README.md
- docs/INSTALL.md
containerd projects (including subprojects) have renamed the default branch from master to main.
> Rename master branch to main branch for containerd projects

- cmd/ctr-remote/commands/flags.go
The `ctr run` command has the `env-file` option and it is handy. I think it would be nice to have it in the optimizer.
Signed-off-by: Jun Lin Chen <webmaster@mc256.com>
> Add env-file option to the optimize command

- .github/dependabot.yml
- Dockerfile
- go.mod
- script/cri-containerd/test.sh
- script/cri-o/test.sh
- script/generated-files/generate.sh
- script/optimize/test.sh
- script/util/make.sh
- script/util/utils.sh
This commit enables dependabot for gomod, Dockerfile and Github Actions.
Detailed guide can be found in:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates
Versions of tools (critools, cni, golang base image, nerdctl, etc.) in CI now refer to the toplevel Dockerfile.
> Enable dependabot

- fs/config/config.go
- fs/remote/resolver.go
Stargz-snapshotter has a mechanism to support registries that do not allow multiple ranges in a single GET request. For the fallback mechanism to kick in, the snapshotter expects the registry to return an error.
Some registries like AWS ECR neither support retrieving multiple ranges of data per GET request nor return an error. Instead they send back the entire requested object.
This patch enables users to configure the fetcher to use single range mode.
Changes:
1) fs/config/config.go: Added a field 'ForceSingleRangeMode' in BlobConfig, corresponding to 'force_single_range_mode' in config.toml
2) fs/remote/resolver.go: Checks whether blobConfig.ForceSingleRangeMode is true; if it is, the fetcher is set to single range mode using fetcher.singleRangeMode()
Signed-off-by: Rishabh Singhvi …
> Allow users to manually set the fetcher to use single range mode 

- cmd/containerd-stargz-grpc/main.go
- fs/fs.go
- fs/layer/node.go
- fs/metrics/common/metrics.go
- fs/metrics/layer/layer.go
- fs/metrics/layer/metrics.go
- fs/remote/resolver.go
- store/pool.go
Hello Container community,
I’m new to the container ecosystem and in the early stages of exploring stargz snapshotter. While exploring the stargz snapshotter, I saw that it does not emit many metrics and it’s really challenging to get alerted if something goes wrong as well as to measure performance characteristics of lazy loading. 
Currently stargz snapshotter emits only 2 metrics: layer_fetched_size and layer_size. In addition to those metrics, I suggest adding the following:    
* Image and layer metrics
* Prefetch bytes per layer (or prefetch ratio)
* Quantifying accuracy of prefetch files
* Number of cache hits
* Total on-demand bytes served out of cache
* Number of on-demand file fetches (aka cache miss)
* Total bytes fetched on-demand
* Latency between mounting a layer and last …
> Latency metrics design proposal

- docs/overview.md
Noticed this link didn't work so made a quick edit so it does.
> Fix broken link in docs/overview.md

- cmd/ctr-remote/commands/optimize.go
- docs/ctr-remote.md
- nativeconverter/estargz/estargz.go
Currently, there is no way for users to specify the GZIP compresssion level when optimizing their images to eStargz format, using the ctr-remote tool.
This commit adds a new flag to the 'optimize' subcommand: estargz-compression-level (similar to the flag in convert subcommand) which defaults to 9. Users can specify compression level using --estargz-compression-level <value> while optimizing the image.
Also, changes to ctr-remote.md explaining the new flag and its usage.
Updated code with suggested changes in https://github.com/containerd/stargz-snapshotter/issues/366#issuecomment-878375257.
> Allow users to specify a GZIP compression level during optimize

- cache/cache.go
- fs/config/config.go
- fs/layer/layer.go
This commit adds `direct=true/false` to the cache configuration of config.toml.
When it's true, cache always works in "direct" mode that doesn't hold data in memory buffers.
```toml
[directory_cache]
direct = true
```
Can be used to avoid #369.
cc @rdpsin
> Add `direct` field for cache configuration in config.toml

- Dockerfile
- go.mod
- go.sum
Alternative of https://github.com/containerd/stargz-snapshotter/pull/373
> Bump containerd to v1.5.3 and nerdctl to v0.10.0

- go.mod
```
- Stargz Snapshotter(`containred-stargz-grpc`)
- Allow users to manually set the fetcher to use single range mode (#350), thanks @rdpsin
- Adds new latency metrics (mount, readdir, registry access) and skeleton for additional ones (#358), thanks @vkuzniet
- Enable to configure `direct` mode of cache through config.toml (#372)
- `ctr-remote`
-  Add env-file option to the optimize command (#345), thanks @mc256
-  Allow users to specify a GZIP compression level during optimize (#368), thanks @rdpsin
- docs
-  Fix a link of OCI Distribution Spec (#338) thanks @knqyf263
-  Fix broken link in docs/overview.md (#362) thanks @IRCody
-  Promote `--oci` option for ctr-remote (#339)
```
> Prepare for v0.7.0

- cmd/ctr-remote/commands/flags.go
- docs/ctr-remote.md
Currently, networking inside a container when optimizing through the ctr-remote tool is only
available through CNI-based networking plugins, not through `net-host`.  Furthermore, there is no option to enable GPUs
inside the container when optimizing GPU-based images.
This commit adds flags to the optimize command to enable both features.
Changes:
1) Added `net-host` flag to enable to networking inside the container, similar to when using `ctr-remote run`.
2) Added `gpus` flag to enable GPU-based image optimization.
3) Changes to documentation explaining the above made changes.
Signed-off-by: Rishabh Singhvi <rdpsin@amazon.com>
> Enable GPUs and networking in container during optimize

- fs/remote/resolver.go
- service/keychain/dockerconfig/dockerconfig.go
stargz-snapshotter reads creds from docker store only at startup time. The
credentials stored in docker config can get periodically rotated.
If stargz-snapshotter is running for extended time on a host before an image is
launched the current mechanism fails because rotated creds are not re-read.
This patch reads creds file everytime authorizer invokes the
'credentials' function and handles cred rotation.
Signed-off-by: Sumeet Bhatia <sumee@amazon.com>
> dockerconfig: Add support for creds rotation to docker store

- fs/config/config.go
- fs/fs.go
stargz-snapshotter currently sets fuse timeout values to one second. Container
images are immutable and hence some applications may want to set higher
timeout values.
This patch makes the timeout values configurable.
Signed-off-by: Sumeet Bhatia <sumee@amazon.com>
> Make fuse timeout values configurable

- fs/config/config.go
- fs/remote/blob.go
- fs/remote/blob_test.go
- fs/remote/resolver.go
stargz-snapshotter fetches entire prefetch range using a single HTTP GET request.
This reduces number of requests to remote registry. However some registries give
better throughput with multiple concurrent requests rather than a single GET request.
This patch adds a configurable parameter to enable users to decide the optimal
prefetch chunk size for their registries.
Signed-off-by: Sumeet Bhatia <sumee@amazon.com>
> Allow users to configure prefetch chunk size

- cmd/ctr-remote/commands/optimize.go
- estargz/estargz.go
- estargz/estargz_test.go
- fs/fs.go
- fs/layer/layer.go
- fs/layer/layer_test.go
- fs/metrics/common/metrics.go
- fs/metrics/layer/layer.go
- fs/reader/reader.go
- fs/reader/reader_test.go
- fs/remote/resolver.go
- snapshot/snapshot.go
This PR adds the metrics for container image launch.
The list of metrics is as follows: 
- Prefetch bytes per layer 
- GET latency for stargz header 
- GET latency for stargz footer 
- GET latency for stargz TOC 
- Latency to deserialize json TOC 
- Total time container launch is blocked on prefetch complete
Signed-off-by: Viktor Kuznietsov <vkuzniet@amazon.com>
> Add image launch metrics

- docs/INSTALL.md
Though this link is too detailed and isn't really helpful, this link is hard to
maintain because it easily becomes out-of-date on each release. Let's remove
this.
> Remove too detailed download link

- analyzer/analyzer.go
Added a message that will print after the period to monitor access logs times out. Currently, the message displayed provides no indication why the task was killed.
Signed-off-by: Rishabh Singhvi <rdpsin@amazon.com>
> Added helpful message whenever optimize period expires

- fs/fs.go
- fs/fs_test.go
- fs/layer/layer.go
- fs/layer/layer_test.go
- fs/layer/node.go
- fs/layer/node_test.go
- fs/metrics/common/metrics.go
- fs/reader/reader.go
- fs/reader/reader_test.go
This PR adds the following metrics:
- Time to download prefetch data
- Time to decompress prefetch data
- Total time to complete prefetch
- Time to download background fetch data
- Time to decompress background fetch data
- Total time to complete background fetch
- Request latency for on-demand reads
- Number of on-demand file access
- Number of on-demand file fetches from remote registry
- Total on-demand bytes served
- Total on-demand bytes fetched from the remote registry
- Latency between mounting a layer and last on-demand fetch for that layer
I added a few metrics as logs, since they represent once per image launch events (prefetch, background fetch decompress and total time, latency between mounting a layer and last on-demand fetch for that layer).
Signed-off-by: Viktor Kuznietsov …
> Add lazy loading metrics

- .golangci.yml
- Makefile
The first commit is fixing Makefile. The second commit is actually upgrading golangci-lint.
> Upgrade golangci-lint from v1.39.0 to v1.42.0

- cmd/containerd-stargz-grpc/main.go
- cmd/containerd-stargz-grpc/server.go
As like containerd, this change adds a few /debug/ endpoints. They can
be used from `ctr pprof` command.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
> Add /debug/ endpoints to expose diagnostic information

- go.mod
Release note:
```
This release includes [zstd:chunked](https://github.com/containers/storage/pull/775) support, improvements on log/metrics/config of Stargz Snapshotter/Store, new NW/GPU options for ctr-remote optimizer and bugfixes.
- estargz
- Made estargz compression-algorithm-agnostic and added support for opening/creating [zstd:chunked](https://github.com/containers/storage/pull/775) (#293)
- Stargz Store
- Enabled to release resources when no reference to a layer (#433)
- Stargz Snapshotter
- Enabled lazy pulling of [zstd:chunked](https://github.com/containers/storage/pull/775) (#293)
- Added more log lines (#394), thanks to @iamsumee
- Added support for creds rotation to docker store (#406), thanks to @iamsumee
- Made fuse timeout values configurable (#407), thanks to @iamsumee
- …
```
> Prepare for v0.8.0

- script/benchmark/test.sh
- script/benchmark/tools/percentiles.sh
"make benchmark" needs multiple environment variables to be set
correctly.
~This change makes some of them optional. The rest are~
The only remaining environment variable is
- BENCHMARK_TARGETS
- ~BENCHMARK_RUNTIME_MODE~
- ~DOCKER_BUILDKIT~
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
> Reduce required environment variables on "make benchmark"

- cache/cache.go
- fs/layer/layer.go
- fs/reader/reader.go
Most of bytes.Buffer in stargz-snapshotter is unbounded in terms of
size and sync.Pool's Get may choose to ignore the pool.
Resizing a buffer before returning to the pool may alleviate the
snapshotter's memory utilization issue.
https://github.com/golang/go/issues/23199 has a long discussion about
the issue.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
> Reset bytes.Buffer before returning it to sync.Pool

- fs/remote/blob.go
- fs/remote/blob_test.go
- fs/remote/resolver.go
stargz snapshotter does not have the mechanism to prevent downloading the same data (or overlapping data) from the registry multiple times. This leads to waste of network bandwidth as it ends up fetching the same bytes multiple times.
Following log lines record the fact that this is happening (the logs were added to `fetchRange` function in `fs/remote/blob.go` and are not the part of this PR):
`
time="2021-08-09T22:33:27.134794144Z" level=debug msg="request header=map[Accept-Encoding:[identity] Range:[bytes=167772160-168820735]] layer=sha256:8ea1027575e92df4962031bccc31de8d8ee052960a50b7649a1f964c50bef79c."
time="2021-08-09T22:33:27.135094521Z" level=debug msg="request header=map[Accept-Encoding:[identity] Range:[bytes=167772160-168820735]] …
> Avoid downloading the same data from the registry multiple times

- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
Alternative of https://github.com/containerd/stargz-snapshotter/pull/462 https://github.com/containerd/stargz-snapshotter/pull/463
> Bump github.com/klauspost/compress from 1.13.5 to 1.13.6

- estargz/estargz.go
- fs/fs.go
- fs/layer/layer.go
- fs/layer/layer_test.go
- fs/reader/reader.go
- fs/reader/reader_test.go
Fixes https://github.com/containerd/stargz-snapshotter/issues/461
Currently, pre/background fetch cannot be called before layer verification so are not started simultaneously. This is because each of them needs to be invoked after the layer verification (`*VerifiableReader.SkipVerify()` or `*VerifiableReader.VerifyTOC()`) to make sure the fetched contents are expected. However, this behaviour slows down prefetch start in some cases.
This commit fixes this issue by allowing pre/background fetch to called before the layer verification. Any verification error before the layer verification is recorded and reported when the verification is performed.
The filesystem calls pre/background fetch immediately after the resolving completes. If the verification is required and an error is reported, it …
> fs: allow pre/background-fetch to be called before layer verification

- go.mod
Release note:
```
This release comes with performance fixes of snapshotter implementation and lossless compression of eStargz.
- estargz
- Support lossless compression (#453)
- Stargz Store
- Add logging of statFile errors (#442), thanks to @vkuzniet
- Reset bytes.Buffer before returning it to sync.Pool (#448), thanks to @kzys
- Avoid downloading the same data from the registry multiple times (#446), thanks to @vkuzniet
- Start pre/background-fetch of layers in an image simultaneously (#467)
- CI
- Reduce required environment variables on "make benchmark" (#441), thanks to @kzys
- Run ctr pprof against containerd-stargz-grpc in Hello Bench (#445), thanks to @kzys
- Add test with upstream k3s (#447)
- Add test with k3s + argo workflow (#449)
```
> Prepare for v0.9.0

- cmd/containerd-stargz-grpc/main.go
- fs/config/config.go
- fs/remote/blob.go
- fs/remote/resolver.go
- fs/remote/resolver_test.go
- go.mod
- go.sum
- service/resolver/cri.go
- service/resolver/registry.go
Currently, the snapshotter does not support retries when sending out HTTP requests.
Any kind of intermittent networking error (such as networking failures or error status codes)
can potentially disrupt existing container workloads.
This patch uses [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) to implement retries in case of network error.
It also handles cases where the server replies with either a 429 or 5xx status code.
Signed-off-by: Rishabh Singhvi <rdpsin@amazon.com>
> Make HTTP requests retryable

- fs/fs.go
- fs/layer/layer.go
- fs/layer/node.go
- fs/metrics/common/metrics.go
- fs/remote/resolver.go
Add new measurement in microseconds for metrics.
Now using `commonmetrics.MeasureLatencyInMilliseconds(...)` for measuring in milliseconds to metrics and `commonmetrics.MeasureLatencyInMicroseconds(...)` for microsecond. As demanded, latency of`node_readdir` and `read_on_demand` now measured by microseconds.
> Add microsecond to metrics

- cmd/go.mod
- go.mod
```
This release comes with experimental support for image distribution on IPFS with lazy pulling ([`/docs/ipfs.md`](/docs/ipfs.md)), support for storing filesystem metadata on disk (bbolt) and reorganization of eStargz documents.
This release introduces new go modules `ipfs` and `cmd`.
We have the following go modules as of now.
- `github.com/containerd/stargz-snapshotter` : Plugins for container runtimes to enable lazy pulling of eStargz and the image creation.
- `github.com/containerd/stargz-snapshotter/estargz` : Utilities to create and manipulate eStargz.
- `github.com/containerd/stargz-snapshotter/ipfs` : Plugins for containerd to support IPFS
- `github.com/containerd/stargz-snapshotter/cmd` : CLI commands
- modules
- Introduce the following go modules (#511)
- `ipfs`: Plugins for …
```
> Prepare for v0.10.0

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- ipfs/go.mod
- ipfs/go.sum
- store/refs.go
- util/containerdutil/manifest.go
See https://github.com/containerd/containerd/commit/a776a27af54a803657d002e7574a4425b3949f56
Also fixes codes relaeted to mediatype detection to make it stricter.
> Bump up containerd to the latest

- cmd/go.mod
- go.mod
Release note:
```
This release updates containerd to apply [the patch for CVE-2021-41190](https://github.com/containerd/containerd/commit/a776a27af54a803657d002e7574a4425b3949f56).
```
> Prepare for release v0.10.1

- fs/remote/resolver.go
Sometimes logrus prints the following log
```
"logrus_error":"can not add field \"ref\""
```
This commit fixes to avoid this message printed.
> Fix logrus prints format failure logs

- analyzer/analyzer.go
Currently, it will print path only when error happens. Add log when success record path could help to see which file will be prefetched
> feat: log success record path when debug

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
Recently k3s updated supported golang version to 1.17.
> CI: k3s: bump up golang to 1.17

- fs/remote/resolver.go
logrus doesn't support fields with functions which leads to meaningless log messages.
e.g.
```
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: func() (io.ReadCloser, error)
```
This commit eliminates such fields to avoid meaningless logs.
> log: Avoid using unsupported field by logrus

- cache/cache.go
- fs/config/config.go
- fs/layer/layer.go
- store/refs.go
- util/cacheutil/lrucache.go
- util/cacheutil/lrucache_test.go
- util/cacheutil/ttlcache.go
- util/cacheutil/ttlcache_test.go
When `filesystem.Mount` is called for the first layer in an image, stargz-snapshotter resolves all layers in that image in parallel and caches these resolved layers metadata in LRU cache. When `filesystem.Mount` is called for the neighbouring layers of that image, the cached layer can be used for speeding up the mounts.
However, when many pulling of images happen in parallel, layers are soonly evicted from the LRU cache by other image pullings and many cache misses happen. This result to many resource consumption (e.g. fd), many (duplicated) requests to the registry, etc.
This commit solves this by using TTL-based cache instead of LRU cache. TTL cache doesn't have size limitations and manages eviction using TTL of each element. This avoids the above problems of quick evictions and many …
> layer resolver: Avoid many cache misses occur when many pullings of images happen

- cmd/go.mod
- go.mod
```
- Stargz Snapshotter and Stargz Store
- Avoid many cache misses occur when many pullings of images happen (#600)
- Avoid using unsupported field by logrus (#539, #589)
- Prevent potential panic by type inconsistency on sync/atomic (#592)
- ctr-remote
-  Log success record path count (#548), thanks to @jonyhy96
- CI/Docs/Tests/Typo fixes
-  Fix golint issue (#524), thanks to @hs0210
-  Fix some spelling mistakes (#572), thanks to @changweige
```
> Prepare for v0.11.0

- fs/remote/resolver.go
`rand.Int63n` panics if passed value <= 0. https://pkg.go.dev/math/rand#Int63n
Necessary to pass test https://github.com/containerd/stargz-snapshotter/runs/5282251000?check_suite_focus=true
> Fix jitter panics with `invalid argument to Int63n`

- cmd/go.mod
- go.mod
```
This release contains a change to `fs` lib to make the metrics log level configurable (#654).
```
> Prepare for v0.11.1

- fs/layer/node.go
- fs/layer/testutil.go
The filesystem of stargz-snapshotter always returns size `0` when stat a symlink.
```console
File: /usr/lib/x86_64-linux-gnu/libpq.so -> libpq.so.5.13
Size: 0         	Blocks: 0          IO Block: 4096   symbolic link
Device: 1000e3h/1048803d	Inode: 4845        Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 2021-05-11 20:10:35.000000000 +0000
Change: 1970-01-01 00:00:00.000000000 +0000
Birth: -
```
But it needs to be the size of the link name according to man `stat(2)`.
https://man7.org/linux/man-pages/man2/lstat.2.html
>       st_size
>              This field gives the size of the file (if it is a regular
>              file or a symbolic link) in bytes.  The size of a symbolic
>              link is …
> fs: return correct file size of symlink

- cmd/go.mod
- go.mod
```
- fs: return correct file size of symlink (#672)
- snapshotter: make restoring configurable (#659)
```
> Prepare for v0.11.2

- fs/fs.go
- fs/layer/layer.go
- fs/layer/node.go
- fs/layer/testutil.go
- service/service.go
- store/manager.go
Currently, stargz-snapshotter's filesystem adds **both** `"trusted.overlay.opaque"` and `"user.overlay.opaque"` to each opaque directory. But overlayfs uses **either** `"trusted.overlay.opaque"`(userxattr=false) or `"user.overlay.opaque"`(userxattr=true) for the opaque xattr and prevents it to be copied up to the upper. Thus the other (i.e. `"user.overlay.opaque"` when userxattr=false or `"trusted.overlay.opaque"`  when userxattr=true) is treated as a normal xattr and can be copied up.
This behaviour of copying up of the xattr is problematic for BuildKit's overlayfs differ because it mistakenly treats a dir with the **copied up** opaque xattr as an opaque dir and creates unnecessary whiteout files. (this causes https://github.com/moby/buildkit/issues/2720.)
This commit fixes this issue by …
> fs: enable to select the correct opaque xattr

- analyzer/analyzer.go
- analyzer/recorder/recorder_test.go
- cache/cache.go
- cache/cache_test.go
- cmd/containerd-stargz-grpc/db/reader.go
- cmd/containerd-stargz-grpc/db/reader_test.go
- cmd/ctr-remote/commands/flags.go
- estargz/build.go
- estargz/build_test.go
- estargz/estargz.go
- estargz/gzip_test.go
- estargz/testutil.go
- estargz/zstdchunked/zstdchunked_test.go
- fs/layer/layer.go
- fs/layer/testutil.go
- fs/reader/reader.go
- fs/remote/blob.go
- fs/remote/blob_test.go
- fs/remote/resolver.go
- fs/remote/resolver_test.go
- metadata/testutil.go
- service/resolver/cri.go
- snapshot/overlayutils/check.go
- snapshot/snapshot.go
- snapshot/snapshot_test.go
- store/refs.go
- util/testutil/ensurehello.go
`ioutil` has been deprecated in go 1.16.
> Migrate from `ioutil` to `io` and `os`

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- ipfs/go.mod
- ipfs/go.sum
- https://github.com/docker/cli/compare/v20.10.13...v20.10.14
- https://github.com/ipfs/interface-go-ipfs-core/compare/v0.6.0...v0.6.1
> go.mod: Bump up dependencies

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- cmd/go.sum
- go.mod
- go.sum
- script/k3s-argo-workflow/run.sh
- script/k3s/run-k3s.sh
Needed to close: https://bugzilla.redhat.com/show_bug.cgi?id=2067450
Prometheus relase note (Addresses CVE-2022-21698): https://github.com/prometheus/client_golang/releases/tag/v1.11.1
It seems that we need to start maintaining v0.10 because of the following reason:
[Kubernetes v1.23+ can only be built with Go 1.17+](https://github.com/kubernetes/kubernetes/commit/434ce4336ab06b3c34208822d558c0432ada3ad3#r60634685) because `sigs.k8s.io/json` uses functionalities available Go 1.17+.
Stargz snapshotter v0.11+ (depends on k8s.io/* 1.23) also depends on `sigs.k8s.io/json` so it can only be built with Go 1.17+.
This makes it impossible to provide stargz-snapshotter fedora packages for Fedora 35 where [Go 1.16 is the latest available Go compiler](https://src.fedoraproject.org/rpms/golang).
We …
> v0.10: Bump up github.com/prometheus/client_golang to v1.11.1

- cmd/go.mod
- go.mod
```
This release is provided only for environments where Go 1.17+ isn't available to build binaries (e.g. Fedora 35).
Use v0.11+ releases.
- Upgrades github.com/prometheus/client_golang from v1.11.0 to v1.11.1 and addresses CVE-2022-21698 (#724).
```
> Prepare for v0.10.2

- .github/workflows/tests.yml
- Dockerfile
- Makefile
- script/benchmark/test.sh
- script/cri-containerd/test.sh
- script/cri-o/test.sh
- script/integration/test.sh
- script/optimize/test.sh
We'll update go.mod to Go 1.18 after k3s updates go.mod to Go 1.18.
> CI: build with Go 1.18

- cmd/ctr-remote/commands/convert.go
- cmd/ctr-remote/commands/optimize.go
- estargz/build.go
- nativeconverter/estargz/estargz.go
- nativeconverter/zstdchunked/zstdchunked.go
When ctr-remote receives signals during conversion, it currently cannot cancel cleanly and leaves some temp files.
This commit fixes this issue.
cannot cancel cleanly.
```console
INFO[0000] analyzing blob "sha256:345e3491a907bb7c6f1bdddcf4a94284b8b6ddd77eb7d93f09432b17b20f2bbe" 
INFO[0000] analyzing blob "sha256:57671312ef6fdbecf340e5fed0fb0863350cd806c92b1fdd7978adbd02afc5c3" 
INFO[0000] analyzing blob "sha256:5e9250ddb7d0fa6d13302c7c3e6a0aa40390e42424caed1e5289077ee4054709" 
INFO[0000] waiting for 10s ...                          
INFO[0000] container exit with code 0                   
INFO[2022-04-08T02:24:50.396344056Z] shim disconnected                             id=c97ppsfe2ibaaiirntm0
WARN[2022-04-08T02:24:50.396455621Z] cleaning up after shim disconnected …
```
> ctr-remote: ensure cancel cleanly when recieves signals during conversion

- cmd/go.mod
- go.mod
```
- ctr-remote: ensure cancel cleanly when recieves signals during conversion (#733)
- dependencies: Bump up github.com/ipld/go-codec-dagpb from v1.3.0 to v1.3.2 to address https://github.com/advisories/GHSA-g3vv-g2j5-45f2 (#736)
```
> Prepare for v0.11.4

- cmd/go.sum
- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/764
https://github.com/containerd/stargz-snapshotter/pull/765
> Bump github.com/klauspost/compress from 1.15.1 to 1.15.2

- cmd/go.sum
- ipfs/go.mod
- ipfs/go.sum
https://github.com/containerd/stargz-snapshotter/pull/749
https://github.com/containerd/stargz-snapshotter/pull/750
> Bump github.com/ipfs/interface-go-ipfs-core from 0.6.2 to 0.7.0

- cmd/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/778
> Bump github.com/docker/cli from 20.10.14+incompatible to 20.10.15+incompatible

- Dockerfile
- script/kind/run-kind.sh
https://github.com/containerd/stargz-snapshotter/pull/783
This commit includes the fix for tests codes to make it work on Kubernetes v1.24.
Since this version, secret for service account needs to be manually created.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
> Bump up kindest/node to v1.24.0

- cmd/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/788
> Bump github.com/docker/cli from 20.10.15+incompatible to 20.10.16+incompatible

- Dockerfile
- Makefile
- runc v1.1.2: https://github.com/opencontainers/runc/releases/tag/v1.1.2
- nerdctl v0.20.0: https://github.com/containerd/nerdctl/releases/tag/v0.20.0
- Podman v4.1.0: https://github.com/containers/podman/releases/tag/v4.1.0
- CRI-O v1.24.0: https://github.com/cri-o/cri-o/releases/tag/v1.24.0
- containers/common v0.48.0: https://github.com/containers/common/releases/tag/v0.48.0
- cri-tools: https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.24.1
> CI: Bump up dependencies

- cmd/go.sum
- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/798
https://github.com/containerd/stargz-snapshotter/pull/801
> Bump github.com/klauspost/compress from 1.15.4 to 1.15.5

- cmd/go.sum
- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/811
https://github.com/containerd/stargz-snapshotter/pull/810
> Bump github.com/klauspost/compress from 1.15.5 to 1.15.6

- estargz/types.go
`NumLink` is used during mounting the layer but is not defined in estargz spec. This field doesn't need to be encoded to JSON.
main:
```
{
"version": 1,
"entries": [
{
"name": "bin/",
"type": "dir",
"modtime": "2022-04-13T00:24:58Z",
"mode": 16877,
"NumLink": 0
},
```
PR:
```
{
"version": 1,
"entries": [
{
"name": "bin/",
"type": "dir",
"modtime": "2022-04-13T00:24:58Z",
"mode": 16877
},
{
```
> Ignore `NumLink` field when encoding TOC

- docs/estargz.md
distribution-spec/detail.md is deleted by
https://github.com/opencontainers/distribution-spec/commit/edbe27fcffdb28899fff98f81747f8b7980fd590
Change the link to a specific commit id.
Signed-off-by: bin liu <liubin0329@gmail.com>
> Docs: fix broken link

- metadata/memory/reader.go
- metadata/testutil.go
As the IDs are used for computing cache keys, it's important that they
do not change. Prior to this change, background fetching would clone the
reader and populate the cache with entries using possibly incorrect keys.
This patch changes the clone behavior to copy over the original ID
mappings.
Note that I also removed the locks around the ID maps as these maps are
never updated after the reader is created.
Fixes https://github.com/containerd/stargz-snapshotter/issues/842
> Preserve TOC item IDs when cloning memory metadata reader.

- estargz/testutil.go
- metadata/memory/reader.go
- metadata/testutil.go
Following up #843
This commit refactors the code, adds NOTE, and adds tests to make sure the cloned `reader` works correctly.
There were some dead code paths related to hardlinks. So this commit removes them and added tests.
> Refactor metadata store

- cmd/go.sum
- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/862
https://github.com/containerd/stargz-snapshotter/pull/861
> Bump github.com/klauspost/compress from 1.15.8 to 1.15.9

- cmd/containerd-stargz-grpc/db/reader_test.go
- metadata/memory/reader_test.go
- metadata/testutil/testutil.go
Most of importers of `metadata` don't require testutil.
> Move `metadata/testutil.go` to `metadata/testutil/testutil.go`

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
k3s upgraded Go to 1.19 recently https://github.com/k3s-io/k3s/blob/ba62c79f9b501f7c5009fe0d3956009d2294d41d/Dockerfile.dapper#L1
> CI: Use go 1.19 for k3s tests

- script/demo/config.stargz.toml
- service/config.go
- service/service.go
- snapshot/snapshot.go
Related: https://github.com/containerd/stargz-snapshotter/pull/901
On restart, containerd-stargz-grpc doesn't startup if one of the snapshots cannot restore.
This makes us impossible even to manually remove images and snapshots (e.g. by using ctr).
```console
(Kill "registry2:5000")
{"level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs","time":"2022-08-29T16:16:55.765328918Z"}
{"error":"failed to restore remote snapshot: failed to prepare remote snapshot: sha256:6311216555c423c3b445877021293bf0285ab61850216d001a70bebd627743c4: failed to resolve layer: failed to resolve layer \"sha256:ea8aeca69d07706fb87e659f5303278f0a416188e69e14eaecc08e41f4cb6ca0\" from \"registry2:5000/ubuntu:20.04-esgz\": failed to resolve the blob: …
```
> Allow manually remove invalid snapshots on restore

- cmd/go.sum
- go.mod
- go.sum
https://github.com/containerd/stargz-snapshotter/pull/910
> Bump github.com/docker/cli from 20.10.17+incompatible to 20.10.18+incompatible

- Dockerfile
- nerdctl v0.23.0: https://github.com/containerd/nerdctl/releases/tag/v0.23.0
- Podman v4.2.1: https://github.com/containers/podman/releases/tag/v4.2.1
- CRI-O v1.25.0: https://github.com/cri-o/cri-o/releases/tag/v1.25.0
- runc v1.1.4: https://github.com/opencontainers/runc/releases/tag/v1.1.4
- conmon: v2.1.4: https://github.com/containers/conmon/releases/tag/v2.1.4
- pause: migrated from `k8s.gcr.io` to `registry.k8s.io`: https://github.com/kubernetes/kubernetes/blob/a7936658baba02e3ee73324ffe670559f03c188a/CHANGELOG/CHANGELOG-1.25.md#moved-container-registry-service-from-k8sgcrio-to-registryk8sio
> Bump up Podman(4.2.1), CRI-O(1.25.0), runc(1.1.4)

- cmd/go.sum
- estargz/go.mod
- estargz/go.sum
- go.mod
- go.sum
- https://github.com/containerd/stargz-snapshotter/pull/931
- https://github.com/containerd/stargz-snapshotter/pull/930
> Bump github.com/klauspost/compress from 1.15.10 to 1.15.11

- analyzer/analyzer.go
- analyzer/option.go
- cmd/ctr-remote/commands/optimize.go
This commit allows analyzer waiting for substring of a stdout line printed from the container.
When that string is detected by the analyzer, it kills the container without waiting for the timeout period.
This would be useful for optimizing server applications that print messages like `up and running` when it becomes ready.
```console
INFO[0000] analyzing blob "sha256:c229119241af7b23b121052a1cae4c03e0a477a72ea6a7f463ad7623ff8f274b" 
INFO[0000] analyzing blob "sha256:bed41eb8190afeec5847d65441aff83eb0458be472cbdafe21ef03a8fb190b85" 
INFO[0000] analyzing blob "sha256:5e59eaa723f193c889435d757b05fcc030596d2f075c7fecbbd538a53200aa40" 
INFO[0000] analyzing blob "sha256:fd5ad76698193c47aa7a5711c08dc24d97c5cc9d1a40e22a6647f45a6e1389a7" 
INFO[0000] analyzing blob …
```
> ctr-remote: allow analyzer waiting for a line from the container

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- https://github.com/containerd/stargz-snapshotter/pull/937
- https://github.com/containerd/stargz-snapshotter/pull/936
> Bump google.golang.org/grpc from 1.49.0 to 1.50.0

- .github/workflows/kind-image.yml
#715
This commit adds a CI to push Kind node image to ~~`ghcr.io/stargz-containers/${VERSION}-kind`~~ `ghcr.io/containerd/stargz-snapshotter:${VERSION}-kind`namespace on each release.
- Example: [`ghcr.io/ktock/stargz-snapshotter:0.0.0-kind`](https://github.com/ktock/stargz-snapshotter/pkgs/container/stargz-snapshotter/45373809?tag=0.0.0-kind)
- https://github.com/ktock/stargz-snapshotter/actions/runs/3234126466/jobs/5296849182
```console
$ cat /tmp/kindconfig.yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
$ kind create cluster --config=/tmp/kindconfig.yaml --name stargz-demo --image ghcr.io/ktock/stargz-snapshotter:0.0.0-kind
```
> Build and push stargz-snapshotter image usable as a kind node

- cmd/go.mod
- go.mod
```
This release publishes a container image usable as a Kind node to `ghcr.io/containerd/stargz-snapshotter:0.12.1-kind`
$ kind create cluster --name stargz-demo --image ghcr.io/containerd/stargz-snapshotter:0.12.1-kind
kind >= v0.16.0 is recommended as the image is based on `kindest/node:v1.25.2` supported by kind v0.16.0.
See also kind release note: https://github.com/kubernetes-sigs/kind/releases/tag/v0.16.0
- Allow manually remove invalid snapshots on restore (#901)
- ctr-remote: Allow analyzer waiting for a line from the container (#933)
- Build and push stargz-snapshotter image usable as a kind node (#940)
```
> Prepare for v0.12.1

- Dockerfile
- fs/fs.go
- script/util/make.sh
Fixes #340
go-fuse already supports `fusermount3`: https://github.com/hanwen/go-fuse/commit/934a183ed91446d218b5471c4df9f93db039f6e1
> Allow using fusermount3

- fs/fs.go
When we run buildkitd + stargz-snapshotter in rootless mode, we get `operation not permitted` error on prune.
```console
$ buildctl --addr unix:///home/ktock/.local/run/buildkitd.sock prune --all
DEBU[2022-11-07T01:34:58Z] failed to unmount                             dir=/home/ktock/.local/share/buildkit/runc-stargz/snapshots/snapshotter/snapshots/83/fs error="operation not permitted"
WARN[2022-11-07T01:34:58Z] failed to remove directory                    error="failed to remove directory \"/home/ktock/.local/share/buildkit/runc-stargz/snapshots/snapshotter/snapshots/83\": unlinkat /home/ktock/.local/share/buildkit/runc-stargz/snapshots/snapshotter/snapshots/83/fs: device or resource busy" path=/home/ktock/.local/share/buildkit/runc-stargz/snapshots/snapshotter/snapshots/83
``` …
> fs: Try unmount without MNT_FORCE before force unmount

- docs/overview.md
- fs/remote/resolver.go
- fs/remote/resolver_test.go
- service/resolver/registry.go
`header` field allows to set headers to send to the server.
```toml
[[resolver.host."registry2:5000".mirrors]]
host = "registry2:5000"
[resolver.host."registry2:5000".mirrors.header]
x-custom-2 = ["value3", "value4"]
```
> NOTE: Headers aren't passed to the redirected location.
> remote: Support per-registry request headers

- cmd/go.sum
- ipfs/go.mod
- ipfs/go.sum
- https://github.com/containerd/stargz-snapshotter/pull/989
> Bump github.com/ipfs/go-ipfs-files from 0.1.1 to 0.2.0

- docs/integration.md
Signed-off-by: Gaius <gaius.qi@gmail.com>
> docs: add dragonfly detailed documentation

- cmd/go.mod
- go.mod
- Should be merged after:
- https://github.com/containerd/stargz-snapshotter/pull/994
- https://github.com/containerd/stargz-snapshotter/pull/990
- https://github.com/containerd/stargz-snapshotter/pull/987
```
This release enables to optionallly create smaller eStargz images using the following flags for `ctr-rmeote i convert` or `ctr-remote i optimize` (#956).
- `--estargz-external-toc`: Separates TOC JSON into another image (called "TOC image"). The result eStargz doesn't contain TOC so we can expect a smaller size than normal eStargz (refer to [`/docs/estargz.md`](https://github.com/containerd/stargz-snapshotter/blob/v0.13.0/docs/estargz.md#estargz-image-with-an-external-toc-optional) for the related eStargz spec).
- `--estargz-min-chunk-size`: Specifies the minimal number of bytes of …
```
> Prepare for v0.13.0

- Dockerfile
- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- ipfs/go.mod
- ipfs/go.sum
https://github.com/containerd/containerd/releases/tag/v1.6.10
- https://github.com/containerd/stargz-snapshotter/pull/1003
- https://github.com/containerd/stargz-snapshotter/pull/1002
- https://github.com/containerd/stargz-snapshotter/pull/1001
> Bump github.com/containerd/containerd from 1.6.9 to 1.6.10

- script/k3s-argo-workflow/run.sh
- script/k3s/run-k3s.sh
k3s imports snapshotters via `github.com/k3s-io/containerd` since  https://github.com/k3s-io/containerd/commit/6fc4cc65d5db609b93699cc5135bb2f7ab2eecb3
We need to fix our test following that structure.
> Fix k3s test based on the latest project structure

- .github/workflows/tests.yml
- Dockerfile
- Makefile
- docs/rootless.md
- script/podman/config/podman-rootless-stargz-store.service
- script/podman/config/storage.conf
- script/podman/config/test-podman-rootless.sh
- script/podman/run_test.sh
- script/podman/test.sh
This commit adds docs about rootless lazy pulling of eStargz with Podman, nerdctl and BuildKit.
Experimental configuration of Podman + rootless Stargz Store is currently implemented using [`podman unshare`](https://docs.podman.io/en/latest/markdown/podman-unshare.1.html) for putting both of them into the same namespace.
```console
$ podman unshare stargz-store --root $HOME/.local/share/stargz-store/data $HOME/.local/share/stargz-store/store &
$ podman pull ghcr.io/stargz-containers/python:3.9-esgz
```
Current limitation of this approach is `--uidmap` flag of `podman run` doesn't work.
So we mark this configuration as "experimental" and will work on further investigation and improvement for eliminating the limitation.
```console
$ podman run -d --uidmap 0:10000:5000 --rm …
```
> doc: Rootless lazy pulling with Podman, nerdctl and BuildKit

- .github/dependabot.yml
- go.mod
- go.sum
Replace directive for this package has already been removed in containerd's go.mod. https://github.com/containerd/containerd/blob/v1.7.0-beta.2/go.mod
> go.mod: remove replace directive for github.com/urfave/cli

- cmd/go.mod
- go.mod
Should be merged after #1075 and  #1074
```
- stargz-snapshotter
- Refactored IPFS-related logic not to depend on `github.com/ipfs/go-ipfs-http-client` (#1034, #1067)
- Added support for CRI v1 API (#1011, #1075)
- docs
- Added docs about rootless lazy pulling with Podman, nerdctl and BuildKit (#1061)
```
> Prepare for v0.14.0

- cmd/go.mod
- go.mod
```
- stargz-snapshotter
- Fixed IPFS_PATH wasn't recognized (#1082)
```
> Prepare for v0.14.1

- script/cri-containerd/mirror.sh
- script/cri-o/mirror.sh
- script/criauth/mirror.sh
- script/k3s-argo-workflow/run.sh
- script/k3s/mirror.sh
- script/k3s/run-k3s.sh
- script/kind/mirror.sh
- script/optimize/optimize/entrypoint.sh
- script/util/make.sh
This commit fixes recent CI failures
https://github.com/containerd/stargz-snapshotter/actions/runs/4110931069/jobs/7094202458#step:3:687
Fixed via 26d8c703b1a44b74a0de32c15fbb1c46cb217baf
```
fatal: detected dubious ownership in repository at '/go/src/github.com/containerd/stargz-snapshotter'
To add an exception for this directory, call:
git config --global --add safe.directory /go/src/github.com/containerd/stargz-snapshotter
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
https://github.com/containerd/stargz-snapshotter/actions/runs/4075472322/jobs/7021914415#step:7:1816
Fixed via 312c5732f8a75353d5e648c4cc17e59374a4f931
```
github.com/k3s-io/k3s/pkg/daemons/executor imports
k8s.io/kubernetes/cmd/kube-controller-manager/app imports …
```
> Fix CI failures

- docs/INSTALL.md
- docs/integration.md
Moby supports lazy pulling of eStargz since [5c1d6c957b97321c8577e10ddbffe6e01981617a](https://github.com/moby/moby/commit/5c1d6c957b97321c8577e10ddbffe6e01981617a) :tada:
> docs: Add Docker(moby) integration

- script/integration/containerd/entrypoint.sh
- service/cri.go
https://github.com/containerd/stargz-snapshotter/pull/1131 introduced containerd labels but stargz-snapshotter still fails to propagate some labels. This commit fixes this issue.
> labels: correctly propagate extra labels

- fs/remote/resolver.go
- script/integration/containerd/config.stargz.toml
- service/resolver/registry.go
Part of https://github.com/containerd/stargz-snapshotter/issues/1180
When setting up an rhttp client, the structure looks like this:
```
http.Client {
Transport: rhttp.Transport {
Client: rhttp.Client {
HTTPClient: http.Client{}
}
}
}
```
Before this change, the timeout was set on the outer client. When the timeout was reached, the request context was cancelled and no more retries would be attempted by the retryable client. Effectively the timeout was being set for the entire retryable request.
This change moves the timeout to the inner client, making the timeout per-request and the timeout of the entire retryable request is governed by the retry policy.
> Make timeout per-request

- Dockerfile
- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- ipfs/go.mod
- ipfs/go.sum
release: https://github.com/containerd/containerd/releases/tag/v1.7.2
- https://github.com/containerd/stargz-snapshotter/pull/1265
- https://github.com/containerd/stargz-snapshotter/pull/1264
- https://github.com/containerd/stargz-snapshotter/pull/1263
> Bump up containerd to 1.7.2

- .github/workflows/tests.yml
- .golangci.yml
- estargz/build.go
- estargz/build_test.go
- fs/reader/testutil.go
This refactors code and bumps up golangci-lint to v1.53.3: https://github.com/golangci/golangci-lint/releases/tag/v1.53.3
This PR also refactors code to fix the following linter errors:
```
fs/reader/testutil.go:307:10: SA4031: this nil check is always true (staticcheck)
if verifier != nil {
^
fs/reader/testutil.go:297:20: SA4031(related information): this is the value of verifier (staticcheck)
verifier := &failIDVerifier{}
^
build.go:439:11: superfluous-else: if block ends with a break statement, so drop this else and outdent its block (revive)
} else {
return nil, fmt.Errorf("failed to parse tar file, %w", err)
}
build_test.go:415:16: superfluous-else: if block ends with a break statement, so drop this else and outdent its block (revive)
} else {
t.Fatalf("Failed to parse tar file: %v", …
```
> Refactor code and bump up golangci-lint to v1.53.3

- snapshot/snapshot.go
The defer function above checks for the err in the outer scope to determine if it should rollback.
The error in the inner-scope of isRemote is a shadow and when it is an error will not cause a rollback of the transaction.
This causes the bolt transaction to keep the write lock open forever.  Any other attempts at taking a write lock will never succeed.
It is not uncommon for `fs.DiskUsage` to be context canceled as it can take a long time to walk the filesystem.
> fix: rollback snapshot to prevent bolt deadlock

- fs/layer/node.go
We run a modified version of the soci-snapshotter (which is based on the stargz-snapshotter) in production at BuildBuddy and recently enabled the golang race detector in our dev environment. It flagged racy accesses to node.ents and node.entsCached, here are the [logs](https://github.com/containerd/stargz-snapshotter/files/12591490/datarace.txt) (line numbers should be the same). This commit protects access to those two fields with a mutex.
> Protect node.ents and node.entsCached with a mutex in fs/layer/node.go

- fs/layer/node.go
Before this change, stargz-snapshotter set fuse.Attr.Blocks to the number of `blockSize`-byte blocks. go-fuse and linux expect this to be reported as 512-byte blocks.
Since `blockSize` > 512, the number of blocks was under-reported which made the files look sparse to programs that inspected them (e.g. `cp`).
fixes #1386.
---
I ran a ubuntu:23.04 container to see that this fixed the hanging issue:
Before:
```
File: /bin/bash
Size: 1437832   	Blocks: 352        IO Block: 4096   regular file
```
After:
```
File: /bin/bash
Size: 1437832     Blocks: 2816       IO Block: 4096   regular file
File: /bin/bash2
Size: 1437832     Blocks: 2816       IO Block: 4096   regular file
```
> Set fuse.Attr.Blocks to number of 512-byte blocks

- .github/workflows/tests.yml
Recently K3SArgoWorkflow fails and it seems to be because of disk pressure on the ubuntu runner (`Warning  FailedScheduling  4m1s  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..`).
This commit fixes this issue by freeing up more spaces on the runner before running the test.
> CI: Fix K3SArgoWorkflow 

- .github/workflows/release.yml
`hub` CLI has been deprecated: https://github.com/actions/runner-images/issues/8362
> CI: release: Migrate from hub to gh

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- Dockerfile
- script/optimize/optimize/entrypoint.sh
containerd main branch changed plugin API that will be released in containerd v2 and that makes the plugin API not compatible to containerd v1 plugin APIs. We'll migrate to the new API once containerd v2 is released. As of now, just temporary disable the CI test against containerd main branch until we migrate to v2 API.
This is needed to pass CI in all other PRs.
> CI: temporary disable containerd main branch integration test

- cmd/go.mod
- go.mod
```
- Removed support for CRI v1alpha2 API that was deprecated in containerd v1.7 (#1175)
- Make timeout per-request (#1181), thanks to @Kern--
- fix: rollback snapshot to prevent bolt deadlock (#1326), thanks to @goller
- Protect node.ents and node.entsCached with a mutex (#1381), thanks to @iain-macdonald
- Fixed the snapshotter reported incorrect number blocks for a file (#1387), thanks to @Kern--
- chore: pkg imported more than once (#1363), thanks to @testwill
```
> Prepare for v0.15.0

- .github/workflows/release.yml
This fixes the error in the release ci.
I've just noticed this after tagging `v0.15.0`. I won't  remove that tag and I'll create another new release `v0.15.1` for releasing binaries on the github release page. `v0.15.0` will remain not having release page nor binaries.
```
Run RELEASE_TAG="${GITHUB_REF##*/}"
total 28
drwxr-xr-x  7 runner docker 4096 Oct 31 05:18 .
drwxr-xr-x 22 runner docker 4096 Oct 31 05:18 ..
drwxr-xr-x  2 runner docker 4096 Oct 31 05:17 builds-amd64
drwxr-xr-x  2 runner docker 4096 Oct 31 05:18 builds-arm-v7
drwxr-xr-x  2 runner docker 4096 Oct 31 05:18 builds-arm64
drwxr-xr-x  2 runner docker 4096 Oct 31 05:18 builds-ppc64le
drwxr-xr-x  2 runner docker 4096 Oct 31 05:18 builds-s390x
stat /home/runner/work/stargz-snapshotter/stargz-snapshotter/builds/builds-amd64/*: …
```
> fix `gh` invocation release ci

- fs/fs.go
- fs/fs_test.go
Fixes: #1583
When the layer is fully cached on the node, registry connection won't happen so we can skip the checking.
> fs: Check connection only when image isn't fully cached

- script/k3s/run-k3s.sh
- script/optimize/optimize/entrypoint.sh
When no mirror is configured for recent k3s, it generates [containerd's hosts configuration](https://github.com/k3s-io/k3s/blob/364dfd8b89e62bc7816aa4843db8deb6f6fd2978/pkg/agent/templates/templates.go#L43) (hosts.toml) that seems to be treated as invalid by containerd (w/ error `failed to decode hosts.toml" error="invalid host tree`).
This commit is a quick temporary fix for unblocking other PRs but in the future, fixes on k3s should be done.
> CI: Fix k3s test faliure

- store/fs.go
This message is logged within `refnode.Lookup` but mentions `rootnode.Lookup` in the message making it a confusing to distinguish between the other, identical message on line 180.
> Fix log message in refnode.Lookup

- .github/workflows/tests.yml
- .golangci.yml
This also fixes the following linter warnings and errors.
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
WARN [lintersdb] The name "vet" is deprecated. The linter has been renamed to: govet. 
WARN The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
ERRO [linters_context] structcheck: This linter is fully inactivated: it will not produce any reports. 
ERRO [linters_context] varcheck: This linter is fully inactivated: it will not produce any reports. 
```
> Use golangci-lint v1.58.0

- README.md
kontain.me does not support estargz anymore since https://github.com/imjasonh/kontain.me/pull/175.
> Remove kontain.me docs

- .github/workflows/tests.yml
https://github.com/golangci/golangci-lint/releases/tag/v1.59.1
> CI: Bump golangci-lint to 1.59.1

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- store/fs.go
Fixes: #1594
Related to: #1599 , #1705
Based on: #1804 (for passing CRI-O CI)
Issues mentioned in #1594 have been discussed in go-fuse repo (https://github.com/hanwen/go-fuse/issues/520, https://github.com/hanwen/go-fuse/issues/504) and it recently added `OnForget` API (https://github.com/hanwen/go-fuse/issues/504) that can be used for checking if a node is reusable or not.
This commit uses that feature to fix #1594.
> store: use OnForget API for checking if a node is reusable

- cache/cache.go
- cmd/containerd-stargz-grpc/main.go
- fs/config/config.go
- fs/layer/layer.go
- fs/layer/node.go
- fs/layer/testutil.go
- fs/reader/reader.go
Here’s a proposed implementation plan for FUSE passthrough:
1. During the Open phase, attempt to pre-read the entire file instead of reading it in chunks.
2. Utilize the existing cache's Get method to retrieve the fd of the cached file that has been written to local storage.
3. Implement the FilePassthroughFder interface in node.file, allowing the fd from step 2 to be registered with the kernel via go-fuse.
By following this approach, subsequent Read operations would not need to return to user space, and go-fuse would release the registered information when necessary.
for details,
https://github.com/containerd/stargz-snapshotter/issues/1867
> Add FUSE Passthrough Support in Stargz-Snapshotter #1867

- fs/layer/node.go
In go-fuse, if the FilePassthroughFder interface is implemented, an attempt is made to register the fd to the kernel using addBackingID after an open operation. 
To avoid this operation in non-passthrough mode, we now return an exceptional value.
> fuse passthrough: fix PassthroughFd return wrong num to go-fuse

- cache/cache.go
- fs/reader/reader.go
In passthough model, close will be toke over by go-fuse, so file.Close is unnecessary
> fuse passthrough: fix cache files closed by lru in passthrough model

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- ipfs/go.mod
- ipfs/go.sum
This downgrades `go` version in go.mod to `v1.22.0` for solving https://github.com/moby/buildkit/pull/5507#discussion_r1860305720.
This commit will start a new branch `v0.16` for maintaining patches for v0.16.X.
I'll release v0.16.2 from that branch after merging this.
> [v0.16] go.mod: Use 1.22.0 by specifying to google.golang.org/grpc v1.67.1

- fs/reader/reader.go
In GetPassthroughFd, infinite loop prefetchEntireFile may lead to stuck on some destructive occasions，such as removing `/var/lib/containerd-stargz-grpc/snapshotter/*` directly after pulling images.
retry once is enough and is able to avoid stuck
> fuse passthrough: prefetchEntireFile just retry once to avoid exception stuck

- snapshot/snapshot.go
This pr fix err report like this：
```
$ containerd-stargz-grpc
$ containerd-stargz-grpc
{"level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs","time":"2024-12-03T06:42:13.989308992Z"}
{"level":"info","mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs","msg":"Received status code: 401 Unauthorized. Refreshing creds...","src":"docker.io/abushwang/ocs9:read-esgz-lit/sha256:afac68f614f687aed660fdc2dffd9825d7024936940879386365b52a99f6d794","time":"2024-12-03T06:42:14.675377841Z"}
{"layer_sha":"sha256:afac68f614f687aed660fdc2dffd9825d7024936940879386365b52a99f6d794","level":"info","metrics":"latency","msg":"value=0.035318 milliseconds; prefetch_size=0 …
```
> snapshots: add metadata.db for serve cleanup

- nativeconverter/zstdchunked/zstdchunked.go
Carry #1847
This PR fixes the following warning by zstd:chunked converter. This PR fixes that issue by not cleaning up of temporary resources by our own but we rely on containerd's GC instead.
```
WARN[0038] failed to remove tmp uncompressed layer       error="content digest sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef: not found" uncompressedDesc="&{application/vnd.oci.image.layer.v1.tar sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef 1024 [] map[] [] <nil> }"
```
reporoducer:
```
````
> [Carry #1847] Fix zstd:chunked converter error on duplicated blobs

- cmd/go.mod
- go.mod
```
- Fix zstd:chunked converter error on duplicated blobs (#1894)
```
> [v0.16] Prepare for v0.16.3

- fusemanager/fusemanager_test.go
Enable fusemanager in the tests in CI
https://github.com/containerd/stargz-snapshotter/pull/1892#pullrequestreview-2501649696
> fuse-manager: add tests

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- Dockerfile
- script/optimize/optimize/entrypoint.sh
We're now using containerd v2 so tests disabled in #1448 can be reenabled.
> CI: Re-enable builtin tests

- analyzer/fanotify/fanotify.go
- cache/cache.go
- cmd/containerd-stargz-grpc/db/reader.go
- cmd/ctr-remote/commands/flags.go
- cmd/go.mod
- fs/reader/reader.go
- fs/remote/resolver.go
- go.mod
- metadata/testutil/testutil.go
- service/service.go
As titled. The replacement is done by:
1. a `multierror` error (`allErr`) -> `var errs []error`
2. `multierror.Append(allErr, err)` -> `errs = append(errs, err)`
3. `return allErr` -> `return errors.Join(errs)`
And if `errs` is empty slice or if every `error` in `errs` are nil, `return errors.Join(errs)` will also return a nil error.
> replace harshicorp/multierror with errors.Join

- .github/workflows/tests.yml
- analyzer/analyzer.go
Following up #1913
That PR disabled some tests because of configuration errors.
> CI: Fix some tests don't run

- .github/dependabot.yml
1. Move repeated `gomod` sections to a single one by using [`directories`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--) instead of `directory`.
2. Add a few `groups`: update deps matching the `groups` pattern in a single PR.
a. One benefit of this is dependabot will update the deps in all `go.mod`s, thus the CI can pass (otherwise it may fail due to requiring `go mod tidy`.
b. I think a should be true regardless if `groups` is used or not. But from my experience, it seems dependabot only do this for `groups`ed deps, and still open different PRs for different modules if a dep is not part of a group.
> Update gomod dependabot to use directories

- cmd/containerd-stargz-grpc/main.go
- docs/overview.md
- snapshot/snapshot.go
In detach mode, when `containerd-stargz-grpc` exits normally, it sends an Unmount request to the fuse manager. Additionally, during the startup of `containerd-stargz-grpc`, the `restoreRemoteSnapshot` function cleans up previous mountpoints. If there are still running containers at this time, it can lead to issues when the TTL cache expires, resulting in abnormal behavior of the containers.
I considered several solutions:
1. The approach in the current PR, where users should restart `containerd-stargz-grpc` using `SIGKILL`, and then skip the cleanup step in `restoreRemoteSnapshot`.
2. Setting `ResolveResultEntryTTLSec` to an infinitely large value to leverage the TTL cache for ensuring the normal operation of containers. However, this would still lead to failures if the containers attempt …
> fusemanager: fix container fail after ttl timeout in detach mode

- fs/reader/reader.go
During the testing of passthrough with large images, we observed that the containerd-stargz-grpc process was terminated. The reason for this issue is that the content to be merged is currently stored in bufPool, which poses a risk of memory exhaustion.
This commit modifies the implementation to directly write the chunks obtained from prefetchEntireFile to disk, thereby mitigating the risk of running out of memory.
> fuse passthrough: fix oom when running huge images

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
PR by dependabot (#1935) didn't update go.mod in a submodule.
> go.mod: bump github.com/docker/cli to 27.5.0+incompatible

- .github/workflows/tests.yml
- .golangci.yml
- Release note: https://github.com/golangci/golangci-lint/releases/tag/v1.63.4
This PR also disables `redefines-builtin-id` which is already disabled in containerd/containerd.
> CI: golangci-lint v1.63.4

- .github/dependabot.yml
Dependabot seems to only update a dep in all go modoules, if it belongs to a group.
This new group will cover all deps that are not part of an existing group, so they get updated in all go.mod.
I think this will help avoid issues like https://github.com/containerd/stargz-snapshotter/pull/1939, and make dependabot work in most cases.
> Create a dependabot group for all go deps

- fs/remote/blob.go
Close #1948 
Thanks @ChengyuZhu6 for the refactoring patch, I'm going to merge that here with adding a tiny fix.
> [Carry 1948] fs/remote: Refactor blob code to make it more modular

- .github/workflows/tests.yml
update project-checks to v1.2.2 to fix this error in CI, It seems to be the same issue as https://github.com/containerd/nerdctl/pull/3976,
cc @AkihiroSuda 
- before updating to v1.2.2
```
github.com/hashicorp/go-version
github.com/sirupsen/logrus
github.com/vbatts/git-validation/git
github.com/vbatts/git-validation/validate
github.com/vbatts/git-validation/rules/danglingwhitespace
github.com/vbatts/git-validation/rules/dco
github.com/vbatts/git-validation/rules/shortsubject
github.com/vbatts/git-validation/rules/messageregexp
github.com/vbatts/git-validation
go: downloading github.com/kunalkushwaha/ltag v0.3.0
go: github.com/kunalkushwaha/ltag@latest: version constraints conflict:
github.com/kunalkushwaha/ltag@v0.3.0: parsing go.mod:
module declares its path as: github.com/containerd/ltag …
```
> fix required kunalkushwaha error

- docs/passthrough.md
- fs/config/config.go
- fs/layer/layer.go
- fs/layer/node.go
- fs/layer/testutil.go
- fs/reader/reader.go
In passthrough mode, the initial pull of an image requires merging chunks into a file. This process can be time-consuming, especially for large files.
This pr optimizes the merging process by introducing two configuration options: `merge_buffer_size` and `merge_worker_count`. By concurrently reading chunks and caching them for batch writing, we enhance the performance of the initial image pull in passthrough mode.
The principle of concurrent reading is illustrated in the diagram below. 
The `merge_worker_count` corresponds to the number of workers in the diagram, while `merge_buffer_size` corresponds to the size of the buffer in the diagram. Before concurrent reading begins, the buffer area is divided, and each worker is assigned a specific region. This approach allows all workers to …
> concurrent file merging in passthrough mode to reduce initial pull time

- fs/reader/reader.go
- fs/reader/testutil.go
This PR addresses the outstanding issue discussed in [this comment](https://github.com/containerd/stargz-snapshotter/pull/1987#discussion_r1988314111). The following changes are introduced:
1. **New `checkHoles` method**
During the `processBatchChunks`, we now record the starting position and the actual size of the buffer read each time. This information is then validated by the `checkHoles` method to ensure there are no gaps or overwrites in the buffer.
2. **Validation after `w.Write(buffer)`**
We also added validation for the return value after `w.Write(buffer)` to prevent any unknown write errors.
3. **Supplementary test cases**
Additional test cases have been included to cover three scenarios: normal batch processing with validation, batch processing with unhandled chunks, and errors …
> Add buffer validation and tests for passthrough concurrent file merging

- cmd/go.mod
- cmd/go.sum
- go.mod
- go.sum
- ipfs/go.mod
- ipfs/go.sum
- https://github.com/containerd/stargz-snapshotter/pull/2018
> bump golang.org/x/net from 0.35.0 to 0.36.0

- fs/layer/node.go
During my testing with pjdfstest, I encountered a situation where the cases related to the maximum filename length got stuck.
```
prove -r pjdfstest/tests/chmod/02.t
pjdfstest/tests/chmod/02.t ..
```
Upon analyzing the logs, I discovered the following information:
- Test pass log
```
+++ /pjdfstest/pjdfstest pathconf . _PC_NAME_MAX
++ name_max=255
++ namegen_len 255
++ len=255
++ name=
++ :
+++ dd if=/dev/urandom bs=64 count=1
+++ openssl md5
+++ awk '{print $NF}'
++ namepart=8e41e9afda303d0b8626dc889b958c90
++ name=8e41e9afda303d0b8626dc889b958c90
+++ printf %s 8e41e9afda303d0b8626dc889b958c90
+++ wc -c
++ curlen=32
++ '[' 32 -lt 255 ']'
++ :
...
+++ dd if=/dev/urandom bs=64 count=1
+++ openssl md5
+++ awk '{print $NF}'
++ namepart=ffe35295125856b903d3f213885d8deb
++ …
```
> Align the Maximum filename length with the running file system

- fs/reader/reader.go
When a file in the image has a size of 0, attempting to access this file results in the following error, causing a fallback to non-passthrough mode:
```
{"digest":"sha256:20e7644054a8071795c5a1da600e48b6670cc5ce1fe12c6df6b9801efc4cb1cc","error":"passThrough model failed due to node.Open: failed to open blob file for \"f70c2f92426071d3402beccba891fc5047352defec8082a8538d354f45820358\": open /var/lib/containerd-stargz-grpc/stargz/fscache/1605520682/f7/f70c2f92426071d3402beccba891fc5047352defec8082a8538d354f45820358: no such file or directory","fetchedPercent":0,"fetchedSize":0,"level":"error","msg":"statFile error","size":724,"time":"2025-05-08T17:40:41.891697643+08:00"}
```
This issue can be reproduced as follows:
```
touch zero_files
cat Dockerfile
FROM busybox
WORKDIR /data
COPY …
```
> fix no such file error for zero size file in passthrough mode

- cmd/containerd-stargz-grpc/main.go
- docs/overview.md
- fusemanager/fusemanager.go
- script/integration/containerd/entrypoint.sh
- snapshot/snapshot.go
Depends on  #2076
Following up https://github.com/containerd/stargz-snapshotter/pull/1892
When stargz snapshotter receives SIGINT, it perform the graceful exit with explicitly unmounting the mountpoints and releasing the associated resources.
This PR makes this avilablable also in the following situations
- when FUSE manager is killed by SIGINT. The user can use SIGTERM and SIGINT for different porpose
- SIGTERM: Usable for restarting only containerd-stargz-grpc (e.g. for reloading configuration). No need to unmount snapshots because they are managed by the FUSE manager.
- SIGINT: Usable when the user wants to use the graceful exit feature of containerd-stargz-grpc because the user will kill the FUSE manager for node restart, etc.
- when containerd-stargz-grpc is killed by SIGTERM …
> Make graceful restarting available in wider configurations

- README.md
- docs/INSTALL.md
- docs/overview.md
- script/benchmark/config-containerd/etc/containerd/config.toml
- script/config/etc/containerd/config.toml
- script/demo/config.containerd.toml
- script/integration/containerd/entrypoint.sh
Fix #1349
CRI plugins fails to perform GC because it fails to find root direcotry of stargz snapshotter. 
Recent containerd added `proxy_plugins.stargz.exports.root` field to config.toml for solving this issue so this PR leverages that feature.
```
Dec 09 01:25:33 testkind-control-plane kubelet[2645]: E1209 01:25:33.155930    2645 kubelet.go:1467] "Image garbage collection failed once. Stats initialization may not have completed yet" err="get filesystem info: Failed to get the info of the filesystem with mountpoint: failed to get device for dir \"/var/lib/containerd/io.containerd.snapshotter.v1.stargz\": stat failed on /var/lib/containerd/io.containerd.snapshotter.v1.stargz with error: no such file or directory"
```
> Fix GC failure of CRI plugin

- .github/workflows/tests.yml
- Dockerfile
- cmd/containerd-stargz-grpc/fsopts/fsopts.go
- cmd/containerd-stargz-grpc/main.go
- cmd/stargz-fuse-manager/main.go
- docs/overview.md
- fs/config/config.go
- fusemanager/fusemanager.go
- fusemanager/fusemanager_test.go
- fusemanager/service.go
- script/benchmark/hello-bench/reboot_containerd.sh
- script/cri-containerd/test-legacy.sh
- script/cri-containerd/test-stargz.sh
- script/cri-containerd/test.sh
- script/demo/run.sh
- script/integration/containerd/entrypoint.sh
- script/integration/test.sh
- service/config.go
- service/resolver/registry.go
Following up https://github.com/containerd/stargz-snapshotter/pull/1892
This PR enables tests for the FUSE manager. Some changes were needed to pass them.
> CI: test fuse manager

- cmd/containerd-stargz-grpc/db/reader_test.go
- estargz/externaltoc/externaltoc_test.go
- estargz/gzip_test.go
- estargz/testutil.go
- estargz/zstdchunked/zstdchunked_test.go
- fs/layer/layer_test.go
- fs/layer/testutil.go
- fs/reader/reader_test.go
- fs/reader/testutil.go
- metadata/memory/reader_test.go
- metadata/testutil/testutil.go
- util/testutil/util.go
The various `testutil` packages reduce duplication, but exist outside of a `_test.go` package and they, along with all of their dependencies are not pruned via dead code elimination which causes #1760. To cut the dependency without refactoring the tests, this creates a local interface which covers the subset of the `testing.T` methods used by the test helpers. 
Closes https://github.com/containerd/stargz-snapshotter/issues/1760.
> Remove `testing` dependency from code outside tests

- cmd/ctr-remote/commands/flags.go
- docs/ctr-remote.md
Currently, when running containers, tools like nerdctl allow specifying --gpus=all. This PR adds the same capability to ctr-remote.
> ctr-remote: support 'all' for --gpus flag

- script/optimize/optimize/entrypoint.sh
- script/optimize/test.sh
This fixes the recent CI flakiness of `test-optimize`.
> test-optimize: do not rely on the external server for the connectivity check

- script/k3s-argo-workflow/run.sh
- script/k3s/run-k3s.sh
Support for Kubernetes v1.34 is worked in #2122. Until that PR is completed, use k3s v1.33 for now to avoid blocking other PRs because of CI failures.
> CI: use k3s v1.33

- script/k3s-argo-workflow/run.sh
- script/k3s/run-k3s.sh
k3s seems to renamed the default branch in recent days.
> test: k3s: use main branch instead of removed master branch

- cmd/ctr-remote/commands/convert.go
- cmd/ctr-remote/commands/optimize.go
- docs/ctr-remote.md
- estargz/build.go
- nativeconverter/estargz/estargz.go
- nativeconverter/estargz/externaltoc/converter.go
- script/util/make.sh
- util/decompressutil/gzip.go
- util/decompressutil/gzip_test.go
The current code uses Go’s built-in gzip library to decompress gzip-formatted images. However, it was found that decompression using Go’s gzip library is slow (especially for large images), while using command-line decompression tools can improve the decompression speed. In the below 10 examples, using decompression commands achieved at least 32% speedup. 
The containerd community has also discussed and implemented related optimizations, see: https://github.com/containerd/containerd/pull/2640.
Although containerd uses the igzip command for decompression by default (see: https://github.com/containerd/containerd/blob/02eb68472ea11518c419d8866a3a309826bbb3ab/pkg/archive/compression/compression.go#L270 ), above results show that pigz delivers the best performance across most test cases. …
> Using decompression commands to improve the layer decompression speed of gzip-formatted images
